"""event betExceptio

Revision ID: 1f0abc26b139
Revises: 9d288df1d21d
Create Date: 2025-02-07 22:22:51.007284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0abc26b139'
down_revision = '9d288df1d21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_exception', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.String(length=50), server_default='race', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_exception', schema=None) as batch_op:
        batch_op.drop_column('event')

    # ### end Alembic commands ###
