"""bet score float

Revision ID: 31d9b38b2f57
Revises: 98a173fb38c7
Create Date: 2025-01-28 23:35:13.290267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d9b38b2f57'
down_revision = '98a173fb38c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_exception', schema=None) as batch_op:
        batch_op.drop_column('is_custom')

    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('bet_exception', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_custom', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
