"""nuevas tablas y columnas

Revision ID: 4f4095f41149
Revises: c92b5b7481a2
Create Date: 2025-01-28 20:52:52.263032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4095f41149'
down_revision = 'c92b5b7481a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('race', sa.String(length=100), nullable=False),
    sa.Column('parameter_bet_id', sa.Integer(), nullable=False),
    sa.Column('bet_user', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['parameter_bet_id'], ['bet_score.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet_exception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_event_id', sa.Integer(), nullable=False),
    sa.Column('bet', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['race_event_id'], ['race_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bet_race')
    op.drop_table('bet_qualy')
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('options', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.drop_column('options')
        batch_op.drop_column('event')

    op.create_table('bet_qualy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('season_id', sa.INTEGER(), nullable=False),
    sa.Column('race', sa.VARCHAR(length=100), nullable=False),
    sa.Column('parameter_bet_id', sa.INTEGER(), nullable=False),
    sa.Column('bet_user', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['parameter_bet_id'], ['bet_score.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet_race',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('season_id', sa.INTEGER(), nullable=False),
    sa.Column('race', sa.VARCHAR(length=100), nullable=False),
    sa.Column('parameter_bet_id', sa.INTEGER(), nullable=False),
    sa.Column('bet_user', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['parameter_bet_id'], ['bet_score.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bet_exception')
    op.drop_table('bet')
    # ### end Alembic commands ###
