"""Anadir de nuevo bet sin ser unique

Revision ID: 76d1ba29040d
Revises: c1735423f2eb
Create Date: 2025-02-08 18:11:38.462960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d1ba29040d'
down_revision = 'c1735423f2eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bet', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.drop_column('bet')

    # ### end Alembic commands ###
