"""nuevas tabla template bet

Revision ID: 98a173fb38c7
Revises: f3c331538c14
Create Date: 2025-01-28 23:00:25.049083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '98a173fb38c7'
down_revision = 'f3c331538c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('bet_score_id', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['bet_score_id'], ['bet_score.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.drop_column('options')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', sqlite.JSON(), nullable=True))

    op.drop_table('bet_template')
    # ### end Alembic commands ###
