"""is custom bet

Revision ID: 9d288df1d21d
Revises: 31d9b38b2f57
Create Date: 2025-02-07 20:59:26.629833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d288df1d21d'
down_revision = '31d9b38b2f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_exception', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_custom', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_exception', schema=None) as batch_op:
        batch_op.drop_column('is_custom')

    # ### end Alembic commands ###
