"""betScore no null

Revision ID: bafe6d457c90
Revises: e9f8a3088985
Create Date: 2025-02-08 17:38:25.632972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bafe6d457c90'
down_revision = 'e9f8a3088985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=50), server_default=sa.text("'race'"), nullable=False))

    # ### end Alembic commands ###
