"""eliminar para despues crearla sin ser unique

Revision ID: c1735423f2eb
Revises: bafe6d457c90
Create Date: 2025-02-08 18:03:34.500108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1735423f2eb'
down_revision = 'bafe6d457c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.drop_column('bet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bet', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
