"""new columns

Revision ID: c92b5b7481a2
Revises: 
Create Date: 2025-01-23 19:01:40.162035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92b5b7481a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_format', sa.String(length=100), nullable=False, server_default='conventional'))
        batch_op.add_column(sa.Column('time_session1', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_session2', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_session3', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_session4', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_session5', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_events', schema=None) as batch_op:
        batch_op.drop_column('time_session5')
        batch_op.drop_column('time_session4')
        batch_op.drop_column('time_session3')
        batch_op.drop_column('time_session2')
        batch_op.drop_column('time_session1')
        batch_op.drop_column('event_format')

    # ### end Alembic commands ###
