"""Nueva migración después de sincronizar

Revision ID: e272dff4bbce
Revises: 4f4095f41149
Create Date: 2025-01-28 20:57:00.903293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e272dff4bbce'
down_revision = '4f4095f41149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('options', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.drop_column('options')
        batch_op.drop_column('event')

    # ### end Alembic commands ###
