"""betScore actualizado con No unico

Revision ID: e9f8a3088985
Revises: 1f0abc26b139
Create Date: 2025-02-08 17:27:35.747441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f8a3088985'
down_revision = '1f0abc26b139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(length=50), server_default='race', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
