"""nuevas tablas y columnas 2

Revision ID: f3c331538c14
Revises: e272dff4bbce
Create Date: 2025-01-28 21:01:37.601426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c331538c14'
down_revision = 'e272dff4bbce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.String(length=50), server_default='carrera', nullable=False))
        batch_op.add_column(sa.Column('options', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_score', schema=None) as batch_op:
        batch_op.drop_column('options')
        batch_op.drop_column('event')

    # ### end Alembic commands ###
