"""new testing-session table

Revision ID: 06e992816736
Revises: ad6188197cf4
Create Date: 2026-03-30 20:34:05.991985
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e992816736'
down_revision = 'ad6188197cf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testing_event_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('testing_event_id', sa.Integer(), nullable=False),
    sa.Column('session_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('scheduled_start_datetime IS NULL OR scheduled_end_datetime IS NULL OR scheduled_start_datetime < scheduled_end_datetime', name='ck_testing_event_sessions_scheduled_window_order'),
    sa.CheckConstraint('session_order >= 1', name='ck_testing_event_sessions_order_positive'),
    sa.CheckConstraint('start_datetime IS NULL OR end_datetime IS NULL OR start_datetime < end_datetime', name='ck_testing_event_sessions_window_order'),
    sa.ForeignKeyConstraint(['testing_event_id'], ['competition.testing_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('testing_event_id', 'session_order', name='uq_testing_event_sessions_event_order'),
    schema='competition'
    )
    op.create_index('ix_testing_event_sessions_public_id', 'testing_event_sessions', ['public_id'], unique=False, schema='competition')
    op.create_index('ix_testing_event_sessions_testing_event_id', 'testing_event_sessions', ['testing_event_id'], unique=False, schema='competition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_testing_event_sessions_testing_event_id', table_name='testing_event_sessions', schema='competition')
    op.drop_index('ix_testing_event_sessions_public_id', table_name='testing_event_sessions', schema='competition')
    op.drop_table('testing_event_sessions', schema='competition')
    # ### end Alembic commands ###
