"""improving constraints

Revision ID: 11c316719af4
Revises: b8c590a650ef
Create Date: 2026-03-03 12:29:32.668035
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '11c316719af4'
down_revision = 'b8c590a650ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_role_permissions_permission_id', 'role_permissions', ['permission_id'], unique=False, schema='auth')
    op.create_index('ix_role_permissions_role_id', 'role_permissions', ['role_id'], unique=False, schema='auth')
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False, schema='auth')
    op.create_index('ix_user_roles_user_id', 'user_roles', ['user_id'], unique=False, schema='auth')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_username'), table_name='users', schema='auth')
    op.create_index('ix_users_auth_provider', 'users', ['auth_provider'], unique=False, schema='auth')
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False, schema='auth')
    
    # uniques con nombre (mejor que None)
    op.create_unique_constraint("uq_users_username", "users", ["username"], schema="auth")

    # OJO: para email, primero lo convertimos a CITEXT y luego ponemos unique
    op.alter_column(
        "users",
        "email",
        schema="auth",
        existing_type=sa.String(length=255),
        type_=postgresql.CITEXT(),
        existing_nullable=False,
    )

    op.create_unique_constraint("uq_users_email", "users", ["email"], schema="auth")
        
    op.drop_constraint(op.f('bet_picks_bet_id_bet_score_id_key'), 'bet_picks', schema='betting', type_='unique')
    op.create_index('ix_bet_picks_invalid', 'bet_picks', ['bet_id'], unique=False, schema='betting', postgresql_where=sa.text('is_invalid = true'))
    op.create_index('ix_bet_picks_invalidated_by', 'bet_picks', ['invalidated_by_user_id'], unique=False, schema='betting')
    op.create_unique_constraint('uq_bet_picks_bet_score', 'bet_picks', ['bet_id', 'bet_score_id'], schema='betting')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bet_picks_bet_score', 'bet_picks', schema='betting', type_='unique')
    op.drop_index('ix_bet_picks_invalidated_by', table_name='bet_picks', schema='betting')
    op.drop_index('ix_bet_picks_invalid', table_name='bet_picks', schema='betting', postgresql_where=sa.text('is_invalid = true'))
    op.create_unique_constraint(op.f('bet_picks_bet_id_bet_score_id_key'), 'bet_picks', ['bet_id', 'bet_score_id'], schema='betting', postgresql_nulls_not_distinct=False)
    op.drop_constraint("uq_users_email", "users", schema="auth", type_="unique")
    op.drop_constraint("uq_users_username", "users", schema="auth", type_="unique")
    op.drop_index('ix_users_created_at', table_name='users', schema='auth')
    op.drop_index('ix_users_auth_provider', table_name='users', schema='auth')
    op.create_index(op.f('ix_auth_users_username'), 'users', ['username'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.drop_index('ix_user_roles_user_id', table_name='user_roles', schema='auth')
    op.drop_index('ix_user_roles_role_id', table_name='user_roles', schema='auth')
    op.drop_index('ix_role_permissions_role_id', table_name='role_permissions', schema='auth')
    op.drop_index('ix_role_permissions_permission_id', table_name='role_permissions', schema='auth')
    # ### end Alembic commands ###
