"""updating constarins indexes competition

Revision ID: 1f93f7ecd816
Revises: c2f9a6d4b8e1
Create Date: 2026-03-30 14:46:09.787785
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f93f7ecd816'
down_revision = 'c2f9a6d4b8e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_circuits_country_id', 'circuits', ['country_id'], unique=False, schema='competition')
    op.create_index(op.f('ix_competition_circuits_code'), 'circuits', ['code'], unique=True, schema='competition')
    op.create_unique_constraint(None, 'countries', ['iso2'], schema='competition')
    op.add_column('event_sessions', sa.Column('status', sa.Enum('SCHEDULED', 'CANCELLED', 'POSTPONED', 'COMPLETED', name='race_event_status_enum', schema='competition'), server_default=sa.text("'SCHEDULED'"), nullable=False), schema='competition')
    op.add_column('event_sessions', sa.Column('status_reason', sa.String(length=200), nullable=True), schema='competition')
    op.add_column('race_events', sa.Column('round_number', sa.Integer(), nullable=False), schema='competition')
    op.create_index('ix_race_events_circuit_id', 'race_events', ['circuit_id'], unique=False, schema='competition')
    op.create_unique_constraint('uq_race_events_season_round', 'race_events', ['season_id', 'round_number'], schema='competition')
    op.create_index('ix_season_drivers_driver_id', 'season_drivers', ['driver_id'], unique=False, schema='competition')
    op.create_index('ix_season_engines_engine_id', 'season_engines', ['engine_id'], unique=False, schema='competition')
    op.create_index('ix_season_teams_team_id', 'season_teams', ['team_id'], unique=False, schema='competition')
    op.drop_index(op.f('ix_competition_seasons_year'), table_name='seasons', schema='competition')
    op.create_index('ix_seasons_year', 'seasons', ['year'], unique=True, schema='competition')
    op.create_index('uq_seasons_single_active', 'seasons', ['is_active'], unique=True, schema='competition', postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_seasons_single_active', table_name='seasons', schema='competition', postgresql_where=sa.text('is_active = true'))
    op.drop_index('ix_seasons_year', table_name='seasons', schema='competition')
    op.create_index(op.f('ix_competition_seasons_year'), 'seasons', ['year'], unique=True, schema='competition')
    op.drop_index('ix_season_teams_team_id', table_name='season_teams', schema='competition')
    op.drop_index('ix_season_engines_engine_id', table_name='season_engines', schema='competition')
    op.drop_index('ix_season_drivers_driver_id', table_name='season_drivers', schema='competition')
    op.drop_constraint('uq_race_events_season_round', 'race_events', schema='competition', type_='unique')
    op.drop_index('ix_race_events_circuit_id', table_name='race_events', schema='competition')
    op.drop_column('race_events', 'round_number', schema='competition')
    op.drop_column('event_sessions', 'status_reason', schema='competition')
    op.drop_column('event_sessions', 'status', schema='competition')
    op.drop_constraint(None, 'countries', schema='competition', type_='unique')
    op.drop_index(op.f('ix_competition_circuits_code'), table_name='circuits', schema='competition')
    op.drop_index('ix_circuits_country_id', table_name='circuits', schema='competition')
    # ### end Alembic commands ###
