"""add password reset token table

Revision ID: 3c30bb98da8f
Revises: 03c3c8f0c661
Create Date: 2026-03-12 16:00:17.072755
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c30bb98da8f'
down_revision = '03c3c8f0c661'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='auth'
    )
    op.create_index('ix_password_reset_tokens_expires_at', 'password_reset_tokens', ['expires_at'], unique=False, schema='auth')
    op.create_index('ix_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=False, schema='auth')
    op.drop_index(op.f('ix_scores_context_ranking'), table_name='scores', schema='scoring')
    op.create_index('ix_scores_context_ranking', 'scores', ['bet_context_id', 'total_points', 'computed_at', 'user_id'], unique=False, schema='scoring')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_context_ranking', table_name='scores', schema='scoring')
    op.create_index(op.f('ix_scores_context_ranking'), 'scores', ['bet_context_id', 'total_points', 'computed_at'], unique=False, schema='scoring')
    op.drop_index('ix_password_reset_tokens_user_id', table_name='password_reset_tokens', schema='auth')
    op.drop_index('ix_password_reset_tokens_expires_at', table_name='password_reset_tokens', schema='auth')
    op.drop_table('password_reset_tokens', schema='auth')
    # ### end Alembic commands ###
