"""add min length checks for auth descriptions

Revision ID: 3f4e968db5d6
Revises: 1f93f7ecd816
Create Date: 2026-03-30 14:52:31.782316
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4e968db5d6'
down_revision = '1f93f7ecd816'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_context_ranking'), table_name='scores', schema='scoring')
    op.create_index('ix_scores_context_ranking', 'scores', ['bet_context_id', 'total_points', 'computed_at'], unique=False, schema='scoring')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_context_ranking', table_name='scores', schema='scoring')
    op.create_index(op.f('ix_scores_context_ranking'), 'scores', ['bet_context_id', 'total_points', 'computed_at', 'user_id'], unique=False, schema='scoring')
    # ### end Alembic commands ###
