"""add social schema tables and teams

Revision ID: 4131f254ef9e
Revises: 4bd5d5a050bd
Create Date: 2026-03-02 23:14:50.181851
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4131f254ef9e'
down_revision = '4bd5d5a050bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS social")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('join_code', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('teams_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('max_team_size', sa.Integer(), nullable=True),
    sa.CheckConstraint('join_code IS NULL OR (length(join_code) >= 4 AND length(join_code) <= 20)', name='ck_groups_join_code_len'),
    sa.CheckConstraint('length(name) >= 2', name='ck_groups_name_minlen'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_groups_name'),
    schema='social'
    )
    op.create_index('ix_groups_join_code', 'groups', ['join_code'], unique=False, schema='social')
    op.create_table('group_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', 'MODERATOR', name='group_role_enum', schema='social'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['social.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_memberships_group_user'),
    schema='social'
    )
    op.create_index('ix_group_memberships_group_id', 'group_memberships', ['group_id'], unique=False, schema='social')
    op.create_index('ix_group_memberships_group_role', 'group_memberships', ['group_id', 'role'], unique=False, schema='social')
    op.create_index('ix_group_memberships_user_id', 'group_memberships', ['user_id'], unique=False, schema='social')
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('length(name) >= 2', name='ck_teams_name_minlen'),
    sa.ForeignKeyConstraint(['group_id'], ['social.groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'name', name='uq_teams_group_name'),
    schema='social'
    )
    op.create_index('ix_teams_group_id', 'teams', ['group_id'], unique=False, schema='social')
    op.create_table('team_season_aggregates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Numeric(precision=14, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['social.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['competition.seasons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['social.teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='scoring'
    )
    op.create_index('ix_team_season_agg_group_id', 'team_season_aggregates', ['group_id'], unique=False, schema='scoring')
    op.create_index('ix_team_season_agg_rank', 'team_season_aggregates', ['group_id', 'season_id', 'total_points', 'computed_at'], unique=False, schema='scoring')
    op.create_index('ix_team_season_agg_season_id', 'team_season_aggregates', ['season_id'], unique=False, schema='scoring')
    op.create_index('ix_team_season_agg_team_id', 'team_season_aggregates', ['team_id'], unique=False, schema='scoring')
    op.create_index('uq_team_season_agg_group_team_season', 'team_season_aggregates', ['group_id', 'team_id', 'season_id'], unique=True, schema='scoring')
    op.create_table('team_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('CAPTAIN', 'MEMBER', name='team_role_enum', schema='social'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['social.teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_memberships_team_user'),
    schema='social'
    )
    op.create_index('ix_team_memberships_team_id', 'team_memberships', ['team_id'], unique=False, schema='social')
    op.create_index('ix_team_memberships_user_id', 'team_memberships', ['user_id'], unique=False, schema='social')
    op.create_table('team_event_aggregates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('bet_context_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Numeric(precision=14, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bet_context_id'], ['betting.bet_contexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['social.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['social.teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='scoring'
    )
    op.create_index('ix_team_event_agg_ctx_id', 'team_event_aggregates', ['bet_context_id'], unique=False, schema='scoring')
    op.create_index('ix_team_event_agg_group_id', 'team_event_aggregates', ['group_id'], unique=False, schema='scoring')
    op.create_index('ix_team_event_agg_group_team', 'team_event_aggregates', ['group_id', 'team_id'], unique=False, schema='scoring')
    op.create_index('ix_team_event_agg_rank', 'team_event_aggregates', ['group_id', 'bet_context_id', 'total_points', 'computed_at'], unique=False, schema='scoring')
    op.create_index('ix_team_event_agg_team_id', 'team_event_aggregates', ['team_id'], unique=False, schema='scoring')
    op.create_index('uq_team_event_agg_group_team_ctx', 'team_event_aggregates', ['group_id', 'team_id', 'bet_context_id'], unique=True, schema='scoring')
    op.add_column('bet_contexts', sa.Column('group_id', sa.Integer(), nullable=False), schema='betting')
    op.drop_index(op.f('ix_bet_contexts_season_kind'), table_name='bet_contexts', schema='betting')
    op.drop_index(op.f('uq_bet_contexts_race_event'), table_name='bet_contexts', schema='betting', postgresql_where='(race_event_id IS NOT NULL)')
    op.drop_index(op.f('uq_bet_contexts_season_kind_season'), table_name='bet_contexts', schema='betting', postgresql_where="(kind = 'SEASON'::betting.bet_context_kind_enum)")
    op.drop_index(op.f('uq_bet_contexts_testing_event'), table_name='bet_contexts', schema='betting', postgresql_where='(testing_event_id IS NOT NULL)')
    op.create_index('ix_bet_contexts_group_id', 'bet_contexts', ['group_id'], unique=False, schema='betting')
    op.create_index('ix_bet_contexts_group_season_kind', 'bet_contexts', ['group_id', 'season_id', 'kind'], unique=False, schema='betting')
    op.create_index('uq_bet_contexts_group_race_event', 'bet_contexts', ['group_id', 'race_event_id'], unique=True, schema='betting', postgresql_where=sa.text('race_event_id IS NOT NULL'))
    op.create_index('uq_bet_contexts_group_season', 'bet_contexts', ['group_id', 'season_id'], unique=True, schema='betting', postgresql_where=sa.text("kind = 'SEASON'"))
    op.create_index('uq_bet_contexts_group_testing_event', 'bet_contexts', ['group_id', 'testing_event_id'], unique=True, schema='betting', postgresql_where=sa.text('testing_event_id IS NOT NULL'))
    op.create_foreign_key(None, 'bet_contexts', 'groups', ['group_id'], ['id'], source_schema='betting', referent_schema='social', ondelete='CASCADE')
    op.add_column('score_season_aggregates', sa.Column('group_id', sa.Integer(), nullable=False), schema='scoring')
    op.drop_index(op.f('ix_score_season_agg_season_rank'), table_name='score_season_aggregates', schema='scoring')
    op.drop_constraint(op.f('uq_score_season_agg_user_season'), 'score_season_aggregates', schema='scoring', type_='unique')
    op.create_index('ix_score_season_agg_group_id', 'score_season_aggregates', ['group_id'], unique=False, schema='scoring')
    op.create_index('ix_score_season_agg_group_season_rank', 'score_season_aggregates', ['group_id', 'season_id', 'total_points', 'computed_at'], unique=False, schema='scoring')
    op.create_index('ix_score_season_agg_group_user', 'score_season_aggregates', ['group_id', 'user_id'], unique=False, schema='scoring')
    op.create_index('uq_score_season_agg_group_user_season', 'score_season_aggregates', ['group_id', 'user_id', 'season_id'], unique=True, schema='scoring')
    op.create_foreign_key(None, 'score_season_aggregates', 'groups', ['group_id'], ['id'], source_schema='scoring', referent_schema='social', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score_season_aggregates', schema='scoring', type_='foreignkey')
    op.drop_index('uq_score_season_agg_group_user_season', table_name='score_season_aggregates', schema='scoring')
    op.drop_index('ix_score_season_agg_group_user', table_name='score_season_aggregates', schema='scoring')
    op.drop_index('ix_score_season_agg_group_season_rank', table_name='score_season_aggregates', schema='scoring')
    op.drop_index('ix_score_season_agg_group_id', table_name='score_season_aggregates', schema='scoring')
    op.create_unique_constraint(op.f('uq_score_season_agg_user_season'), 'score_season_aggregates', ['user_id', 'season_id'], schema='scoring', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_score_season_agg_season_rank'), 'score_season_aggregates', ['season_id', 'total_points', 'computed_at'], unique=False, schema='scoring')
    op.drop_column('score_season_aggregates', 'group_id', schema='scoring')
    op.drop_constraint(None, 'bet_contexts', schema='betting', type_='foreignkey')
    op.drop_index('uq_bet_contexts_group_testing_event', table_name='bet_contexts', schema='betting', postgresql_where=sa.text('testing_event_id IS NOT NULL'))
    op.drop_index('uq_bet_contexts_group_season', table_name='bet_contexts', schema='betting', postgresql_where=sa.text("kind = 'SEASON'"))
    op.drop_index('uq_bet_contexts_group_race_event', table_name='bet_contexts', schema='betting', postgresql_where=sa.text('race_event_id IS NOT NULL'))
    op.drop_index('ix_bet_contexts_group_season_kind', table_name='bet_contexts', schema='betting')
    op.drop_index('ix_bet_contexts_group_id', table_name='bet_contexts', schema='betting')
    op.create_index(op.f('uq_bet_contexts_testing_event'), 'bet_contexts', ['testing_event_id'], unique=True, schema='betting', postgresql_where='(testing_event_id IS NOT NULL)')
    op.create_index(op.f('uq_bet_contexts_season_kind_season'), 'bet_contexts', ['season_id'], unique=True, schema='betting', postgresql_where="(kind = 'SEASON'::betting.bet_context_kind_enum)")
    op.create_index(op.f('uq_bet_contexts_race_event'), 'bet_contexts', ['race_event_id'], unique=True, schema='betting', postgresql_where='(race_event_id IS NOT NULL)')
    op.create_index(op.f('ix_bet_contexts_season_kind'), 'bet_contexts', ['season_id', 'kind'], unique=False, schema='betting')
    op.drop_column('bet_contexts', 'group_id', schema='betting')
    op.drop_index('uq_team_event_agg_group_team_ctx', table_name='team_event_aggregates', schema='scoring')
    op.drop_index('ix_team_event_agg_team_id', table_name='team_event_aggregates', schema='scoring')
    op.drop_index('ix_team_event_agg_rank', table_name='team_event_aggregates', schema='scoring')
    op.drop_index('ix_team_event_agg_group_team', table_name='team_event_aggregates', schema='scoring')
    op.drop_index('ix_team_event_agg_group_id', table_name='team_event_aggregates', schema='scoring')
    op.drop_index('ix_team_event_agg_ctx_id', table_name='team_event_aggregates', schema='scoring')
    op.drop_table('team_event_aggregates', schema='scoring')
    op.drop_index('ix_team_memberships_user_id', table_name='team_memberships', schema='social')
    op.drop_index('ix_team_memberships_team_id', table_name='team_memberships', schema='social')
    op.drop_table('team_memberships', schema='social')
    op.drop_index('uq_team_season_agg_group_team_season', table_name='team_season_aggregates', schema='scoring')
    op.drop_index('ix_team_season_agg_team_id', table_name='team_season_aggregates', schema='scoring')
    op.drop_index('ix_team_season_agg_season_id', table_name='team_season_aggregates', schema='scoring')
    op.drop_index('ix_team_season_agg_rank', table_name='team_season_aggregates', schema='scoring')
    op.drop_index('ix_team_season_agg_group_id', table_name='team_season_aggregates', schema='scoring')
    op.drop_table('team_season_aggregates', schema='scoring')
    op.drop_index('ix_teams_group_id', table_name='teams', schema='social')
    op.drop_table('teams', schema='social')
    op.drop_index('ix_group_memberships_user_id', table_name='group_memberships', schema='social')
    op.drop_index('ix_group_memberships_group_role', table_name='group_memberships', schema='social')
    op.drop_index('ix_group_memberships_group_id', table_name='group_memberships', schema='social')
    op.drop_table('group_memberships', schema='social')
    op.drop_index('ix_groups_join_code', table_name='groups', schema='social')
    op.drop_table('groups', schema='social')
    # ### end Alembic commands ###
