"""add driver nationality country

Revision ID: 464499485096
Revises: 9b2d4c6f8a10
Create Date: 2026-08-07 12:55:46.474328
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464499485096'
down_revision = '9b2d4c6f8a10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('nationality_country_id', sa.Integer(), nullable=True), schema='competition')
    op.create_index(op.f('ix_competition_drivers_nationality_country_id'), 'drivers', ['nationality_country_id'], unique=False, schema='competition')
    op.create_foreign_key('fk_drivers_nationality_country_id_countries', 'drivers', 'countries', ['nationality_country_id'], ['id'], source_schema='competition', referent_schema='competition', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_drivers_nationality_country_id_countries', 'drivers', schema='competition', type_='foreignkey')
    op.drop_index(op.f('ix_competition_drivers_nationality_country_id'), table_name='drivers', schema='competition')
    op.drop_column('drivers', 'nationality_country_id', schema='competition')
    # ### end Alembic commands ###
