"""add scoring_season_aggregate table

Revision ID: 4bd5d5a050bd
Revises: c4ef249fbf7c
Create Date: 2026-03-02 19:28:45.248170
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd5d5a050bd'
down_revision = 'c4ef249fbf7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_season_aggregates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Numeric(precision=14, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['competition.seasons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'season_id', name='uq_score_season_agg_user_season'),
    schema='scoring'
    )
    op.create_index('ix_score_season_agg_season_id', 'score_season_aggregates', ['season_id'], unique=False, schema='scoring')
    op.create_index('ix_score_season_agg_season_rank', 'score_season_aggregates', ['season_id', 'total_points', 'computed_at'], unique=False, schema='scoring')
    op.create_index('ix_score_season_agg_user_id', 'score_season_aggregates', ['user_id'], unique=False, schema='scoring')
    op.alter_column('score_components', 'points',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               type_=sa.Numeric(precision=14, scale=8),
               existing_nullable=False,
               existing_server_default=sa.text('0'),
               schema='scoring')
    op.alter_column('score_session_components', 'points',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               type_=sa.Numeric(precision=14, scale=8),
               existing_nullable=False,
               existing_server_default=sa.text('0'),
               schema='scoring')
    op.alter_column('score_sessions', 'total_points',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               type_=sa.Numeric(precision=14, scale=8),
               existing_nullable=False,
               existing_server_default=sa.text('0'),
               schema='scoring')
    op.drop_index(op.f('ix_scores_context_ranking'), table_name='scores', schema='scoring')
    op.create_index('ix_scores_context_ranking', 'scores', ['bet_context_id', 'total_points', 'computed_at', 'user_id'], unique=False, schema='scoring')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_context_ranking', table_name='scores', schema='scoring')
    op.create_index(op.f('ix_scores_context_ranking'), 'scores', ['bet_context_id', 'total_points', 'computed_at'], unique=False, schema='scoring')
    op.alter_column('score_sessions', 'total_points',
               existing_type=sa.Numeric(precision=14, scale=8),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False,
               existing_server_default=sa.text('0'),
               schema='scoring')
    op.alter_column('score_session_components', 'points',
               existing_type=sa.Numeric(precision=14, scale=8),
               type_=sa.NUMERIC(precision=12, scale=6),
               existing_nullable=False,
               existing_server_default=sa.text('0'),
               schema='scoring')
    op.alter_column('score_components', 'points',
               existing_type=sa.Numeric(precision=14, scale=8),
               type_=sa.NUMERIC(precision=12, scale=6),
               existing_nullable=False,
               existing_server_default=sa.text('0'),
               schema='scoring')
    op.drop_index('ix_score_season_agg_user_id', table_name='score_season_aggregates', schema='scoring')
    op.drop_index('ix_score_season_agg_season_rank', table_name='score_season_aggregates', schema='scoring')
    op.drop_index('ix_score_season_agg_season_id', table_name='score_season_aggregates', schema='scoring')
    op.drop_table('score_season_aggregates', schema='scoring')
    # ### end Alembic commands ###
