"""updating constrainst indexes social

Revision ID: 4e9d15498622
Revises: af7d0ef53223
Create Date: 2026-03-30 16:01:40.530690
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9d15498622'
down_revision = 'af7d0ef53223'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_teams_group_id_id', 'teams', ['group_id', 'id'], schema='social')
    op.create_index('uq_group_memberships_single_owner', 'group_memberships', ['group_id'], unique=True, schema='social', postgresql_where=sa.text("role = 'OWNER'"))
    op.create_unique_constraint('uq_groups_join_code', 'groups', ['join_code'], schema='social')
    op.create_index('ix_teams_group_active', 'teams', ['group_id', 'is_active'], unique=False, schema='social')
    op.add_column('team_memberships', sa.Column('group_id', sa.Integer(), nullable=False), schema='social')

    op.execute(
        """
        UPDATE social.team_memberships tm
        SET group_id = t.group_id
        FROM social.teams t
        WHERE tm.team_id = t.id
        """
    )

    op.alter_column(
        "team_memberships",
        "group_id",
        existing_type=sa.Integer(),
        nullable=False,
        schema="social",
    )

    op.create_index('ix_team_memberships_group_id', 'team_memberships', ['group_id'], unique=False, schema='social')
    op.create_unique_constraint('uq_team_memberships_group_user', 'team_memberships', ['group_id', 'user_id'], schema='social')
    op.create_index('uq_team_memberships_single_captain', 'team_memberships', ['team_id'], unique=True, schema='social', postgresql_where=sa.text("role = 'CAPTAIN'"))
    op.drop_constraint(op.f('team_memberships_team_id_fkey'), 'team_memberships', schema='social', type_='foreignkey')
    op.create_foreign_key('fk_team_memberships_group_team', 'team_memberships', 'teams', ['group_id', 'team_id'], ['group_id', 'id'], source_schema='social', referent_schema='social', ondelete='CASCADE')
    op.create_foreign_key('fk_team_memberships_group_id_groups', 'team_memberships', 'groups', ['group_id'], ['id'], source_schema='social', referent_schema='social', ondelete='CASCADE')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_team_memberships_group_id_groups",
        "team_memberships",
        schema="social",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_team_memberships_group_team",
        "team_memberships",
        schema="social",
        type_="foreignkey",
    )

    op.create_foreign_key(
        op.f("team_memberships_team_id_fkey"),
        "team_memberships",
        "teams",
        ["team_id"],
        ["id"],
        source_schema="social",
        referent_schema="social",
        ondelete="CASCADE",
    )

    op.drop_index(
        "uq_team_memberships_single_captain",
        table_name="team_memberships",
        schema="social",
        postgresql_where=sa.text("role = 'CAPTAIN'"),
    )
    op.drop_constraint(
        "uq_team_memberships_group_user",
        "team_memberships",
        schema="social",
        type_="unique",
    )
    op.drop_index("ix_team_memberships_group_id", table_name="team_memberships", schema="social")
    op.drop_column("team_memberships", "group_id", schema="social")

    op.drop_index("ix_teams_group_active", table_name="teams", schema="social")
    op.drop_constraint("uq_teams_group_id_id", "teams", schema="social", type_="unique")

    op.drop_constraint("uq_groups_join_code", "groups", schema="social", type_="unique")

    op.drop_index(
        "uq_group_memberships_single_owner",
        table_name="group_memberships",
        schema="social",
        postgresql_where=sa.text("role = 'OWNER'"),
    )
     # ### end Alembic commands ###
