"""new table relation bets

Revision ID: 597920bc863b
Revises: c7b8e2a1f4d9
Create Date: 2026-04-04 21:32:11.579684
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597920bc863b'
down_revision = 'c7b8e2a1f4d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season_drivers', sa.Column('driver_number', sa.Integer(), nullable=True), schema='competition')
    op.create_index('uq_season_drivers_season_driver_number', 'season_drivers', ['season_id', 'driver_number'], unique=True, schema='competition', postgresql_where=sa.text('driver_number IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_season_drivers_season_driver_number', table_name='season_drivers', schema='competition', postgresql_where=sa.text('driver_number IS NOT NULL'))
    op.drop_column('season_drivers', 'driver_number', schema='competition')
    # ### end Alembic commands ###
