"""add betting schema tables

Revision ID: 638e1b8eb6b3
Revises: ed5b25ab81de
Create Date: 2026-03-02 13:07:07.674595
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '638e1b8eb6b3'
down_revision = 'ed5b25ab81de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS betting")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('base_points', sa.Float(), nullable=False),
    sa.Column('value_type', sa.Enum('DRIVER', 'TEAM', 'ENGINE', 'CIRCUIT', 'STRING', 'INTEGER', 'FLOAT', 'BOOLEAN', 'POSITION', name='bet_value_type_enum', schema='betting'), nullable=False),
    sa.Column('constraints_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("code ~ '^[A-Z0-9_]+$'", name='ck_bet_scores_code_format'),
    sa.CheckConstraint('base_points >= 0', name='ck_bet_scores_base_points_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    schema='betting'
    )
    op.create_index('ix_bet_scores_value_type', 'bet_scores', ['value_type'], unique=False, schema='betting')
    op.create_index('uq_bet_scores_code', 'bet_scores', ['code'], unique=True, schema='betting')
    op.create_table('bet_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('context_kind', sa.Enum('GP', 'PRETESTING', 'SEASON', name='bet_context_kind_enum', schema='betting'), nullable=False),
    sa.Column('scope', sa.Enum('EVENT', 'SESSION', name='bet_template_scope_enum', schema='betting'), server_default=sa.text("'EVENT'"), nullable=False),
    sa.Column('session_type', postgresql.ENUM('FP1', 'FP2', 'FP3', 'QUALY', 'SPRINT_QUALY', 'SPRINT', 'RACE', name='event_session_type_enum', schema='competition', create_type=False,), nullable=True),
    sa.CheckConstraint("(  (scope = 'EVENT' AND session_type IS NULL)  OR  (scope = 'SESSION' AND context_kind = 'GP' AND session_type IS NOT NULL))", name='ck_bet_templates_scope_sessiontype'),
    sa.ForeignKeyConstraint(['season_id'], ['competition.seasons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='betting'
    )
    op.create_index('ix_bet_templates_season_kind', 'bet_templates', ['season_id', 'context_kind'], unique=False, schema='betting')
    op.create_index('uq_bet_templates_gp_event', 'bet_templates', ['season_id', 'context_kind', 'scope'], unique=True, schema='betting', postgresql_where=sa.text("context_kind = 'GP' AND scope = 'EVENT'"))
    op.create_index('uq_bet_templates_gp_session', 'bet_templates', ['season_id', 'context_kind', 'scope', 'session_type'], unique=True, schema='betting', postgresql_where=sa.text("context_kind = 'GP' AND scope = 'SESSION'"))
    op.create_index('uq_bet_templates_non_gp', 'bet_templates', ['season_id', 'context_kind'], unique=True, schema='betting', postgresql_where=sa.text("context_kind <> 'GP'"))
    op.create_table('bet_template_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('bet_score_id', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bet_score_id'], ['betting.bet_scores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['betting.bet_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'bet_score_id', name='uq_template_bet_score'),
    sa.UniqueConstraint('template_id', 'display_order', name='uq_template_display_order'),
    schema='betting'
    )
    op.create_index('ix_template_items_bet_score_id', 'bet_template_items', ['bet_score_id'], unique=False, schema='betting')
    op.create_index('ix_template_items_template_id', 'bet_template_items', ['template_id'], unique=False, schema='betting')
    op.create_table('bet_contexts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.Enum('GP', 'PRETESTING', 'SEASON', name='bet_context_kind_enum', schema='betting'), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('race_event_id', sa.Integer(), nullable=True),
    sa.Column('testing_event_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('results_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('results_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("( (kind = 'GP' AND race_event_id IS NOT NULL AND testing_event_id IS NULL) OR  (kind = 'PRETESTING' AND testing_event_id IS NOT NULL AND race_event_id IS NULL) OR  (kind = 'SEASON' AND race_event_id IS NULL AND testing_event_id IS NULL))", name='ck_bet_contexts_kind_matches_ids'),
    sa.CheckConstraint('NOT (race_event_id IS NOT NULL AND testing_event_id IS NOT NULL)', name='ck_bet_contexts_not_both_event_ids'),
    sa.CheckConstraint('results_published = false OR results_published_at IS NOT NULL', name='ck_bet_contexts_published_requires_timestamp'),
    sa.CheckConstraint('results_published = true OR results_published_at IS NULL', name='ck_bet_contexts_unpublished_has_no_timestamp'),
    sa.ForeignKeyConstraint(['race_event_id'], ['competition.race_events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['competition.seasons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['testing_event_id'], ['competition.testing_events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='betting'
    )
    op.create_index('ix_bet_contexts_kind', 'bet_contexts', ['kind'], unique=False, schema='betting')
    op.create_index('ix_bet_contexts_season_id', 'bet_contexts', ['season_id'], unique=False, schema='betting')
    op.create_index('ix_bet_contexts_season_kind', 'bet_contexts', ['season_id', 'kind'], unique=False, schema='betting')
    op.create_index('uq_bet_contexts_race_event', 'bet_contexts', ['race_event_id'], unique=True, schema='betting', postgresql_where=sa.text('race_event_id IS NOT NULL'))
    op.create_index('uq_bet_contexts_season_kind_season', 'bet_contexts', ['season_id'], unique=True, schema='betting', postgresql_where=sa.text("kind = 'SEASON'"))
    op.create_index('uq_bet_contexts_testing_event', 'bet_contexts', ['testing_event_id'], unique=True, schema='betting', postgresql_where=sa.text('testing_event_id IS NOT NULL'))
    op.create_table('bet_exceptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bet_context_id', sa.Integer(), nullable=False),
    sa.Column('event_session_id', sa.Integer(), nullable=True),
    sa.Column('bet_score_id', sa.Integer(), nullable=False),
    sa.Column('override_points', sa.Float(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('override_constraints_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.CheckConstraint('override_points IS NOT NULL OR is_disabled IS NOT NULL OR override_constraints_json IS NOT NULL', name='ck_bet_exceptions_has_effect'),
    sa.CheckConstraint('override_points IS NULL OR override_points >= 0', name='ck_bet_exceptions_override_points_nonneg'),
    sa.ForeignKeyConstraint(['bet_context_id'], ['betting.bet_contexts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bet_score_id'], ['betting.bet_scores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_session_id'], ['competition.event_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='betting'
    )
    op.create_index('ix_bet_exceptions_context_id', 'bet_exceptions', ['bet_context_id'], unique=False, schema='betting')
    op.create_index('ix_bet_exceptions_score_id', 'bet_exceptions', ['bet_score_id'], unique=False, schema='betting')
    op.create_index('ix_bet_exceptions_session_id', 'bet_exceptions', ['event_session_id'], unique=False, schema='betting')
    op.create_index('uq_bet_exceptions_context_score_nosession', 'bet_exceptions', ['bet_context_id', 'bet_score_id'], unique=True, schema='betting', postgresql_where=sa.text('event_session_id IS NULL'))
    op.create_index('uq_bet_exceptions_context_session_score', 'bet_exceptions', ['bet_context_id', 'event_session_id', 'bet_score_id'], unique=True, schema='betting', postgresql_where=sa.text('event_session_id IS NOT NULL'))
    op.create_table('bets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bet_context_id', sa.Integer(), nullable=False),
    sa.Column('event_session_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('locked_at IS NULL OR submitted_at IS NULL OR locked_at >= submitted_at', name='ck_bets_locked_after_submit'),
    sa.ForeignKeyConstraint(['bet_context_id'], ['betting.bet_contexts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_session_id'], ['competition.event_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='betting'
    )
    op.create_index('ix_bets_context_ranking', 'bets', ['bet_context_id', 'last_modified_at', 'id'], unique=False, schema='betting', postgresql_where=sa.text('submitted_at IS NOT NULL'))
    op.create_index('ix_bets_ctx_session_ranking', 'bets', ['bet_context_id', 'event_session_id', 'last_modified_at', 'id'], unique=False, schema='betting', postgresql_where=sa.text('submitted_at IS NOT NULL'))
    op.create_index('ix_bets_user_context', 'bets', ['user_id', 'bet_context_id'], unique=False, schema='betting')
    op.create_index('uq_bets_user_ctx_session_notnull', 'bets', ['user_id', 'bet_context_id', 'event_session_id'], unique=True, schema='betting', postgresql_where=sa.text('event_session_id IS NOT NULL'))
    op.create_index('uq_bets_user_ctx_session_null', 'bets', ['user_id', 'bet_context_id'], unique=True, schema='betting', postgresql_where=sa.text('event_session_id IS NULL'))
    op.create_table('bet_picks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('bet_score_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('is_invalid', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('invalid_reason', sa.String(length=300), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bet_id'], ['betting.bets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bet_score_id'], ['betting.bet_scores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invalidated_by_user_id'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bet_id', 'bet_score_id'),
    schema='betting'
    )
    op.create_index('ix_bet_picks_bet_id', 'bet_picks', ['bet_id'], unique=False, schema='betting')
    op.create_index('ix_bet_picks_score_id', 'bet_picks', ['bet_score_id'], unique=False, schema='betting')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bet_picks_score_id', table_name='bet_picks', schema='betting')
    op.drop_index('ix_bet_picks_bet_id', table_name='bet_picks', schema='betting')
    op.drop_table('bet_picks', schema='betting')
    op.drop_index('uq_bets_user_ctx_session_null', table_name='bets', schema='betting', postgresql_where=sa.text('event_session_id IS NULL'))
    op.drop_index('uq_bets_user_ctx_session_notnull', table_name='bets', schema='betting', postgresql_where=sa.text('event_session_id IS NOT NULL'))
    op.drop_index('ix_bets_user_context', table_name='bets', schema='betting')
    op.drop_index('ix_bets_ctx_session_ranking', table_name='bets', schema='betting', postgresql_where=sa.text('submitted_at IS NOT NULL'))
    op.drop_index('ix_bets_context_ranking', table_name='bets', schema='betting', postgresql_where=sa.text('submitted_at IS NOT NULL'))
    op.drop_table('bets', schema='betting')
    op.drop_index('uq_bet_exceptions_context_session_score', table_name='bet_exceptions', schema='betting', postgresql_where=sa.text('event_session_id IS NOT NULL'))
    op.drop_index('uq_bet_exceptions_context_score_nosession', table_name='bet_exceptions', schema='betting', postgresql_where=sa.text('event_session_id IS NULL'))
    op.drop_index('ix_bet_exceptions_session_id', table_name='bet_exceptions', schema='betting')
    op.drop_index('ix_bet_exceptions_score_id', table_name='bet_exceptions', schema='betting')
    op.drop_index('ix_bet_exceptions_context_id', table_name='bet_exceptions', schema='betting')
    op.drop_table('bet_exceptions', schema='betting')
    op.drop_index('uq_bet_contexts_testing_event', table_name='bet_contexts', schema='betting', postgresql_where=sa.text('testing_event_id IS NOT NULL'))
    op.drop_index('uq_bet_contexts_season_kind_season', table_name='bet_contexts', schema='betting', postgresql_where=sa.text("kind = 'SEASON'"))
    op.drop_index('uq_bet_contexts_race_event', table_name='bet_contexts', schema='betting', postgresql_where=sa.text('race_event_id IS NOT NULL'))
    op.drop_index('ix_bet_contexts_season_kind', table_name='bet_contexts', schema='betting')
    op.drop_index('ix_bet_contexts_season_id', table_name='bet_contexts', schema='betting')
    op.drop_index('ix_bet_contexts_kind', table_name='bet_contexts', schema='betting')
    op.drop_table('bet_contexts', schema='betting')
    op.drop_index('ix_template_items_template_id', table_name='bet_template_items', schema='betting')
    op.drop_index('ix_template_items_bet_score_id', table_name='bet_template_items', schema='betting')
    op.drop_table('bet_template_items', schema='betting')
    op.drop_index('uq_bet_templates_non_gp', table_name='bet_templates', schema='betting', postgresql_where=sa.text("context_kind <> 'GP'"))
    op.drop_index('uq_bet_templates_gp_session', table_name='bet_templates', schema='betting', postgresql_where=sa.text("context_kind = 'GP' AND scope = 'SESSION'"))
    op.drop_index('uq_bet_templates_gp_event', table_name='bet_templates', schema='betting', postgresql_where=sa.text("context_kind = 'GP' AND scope = 'EVENT'"))
    op.drop_index('ix_bet_templates_season_kind', table_name='bet_templates', schema='betting')
    op.drop_table('bet_templates', schema='betting')
    op.drop_index('uq_bet_scores_code', table_name='bet_scores', schema='betting')
    op.drop_index('ix_bet_scores_value_type', table_name='bet_scores', schema='betting')
    op.drop_table('bet_scores', schema='betting')
    # ### end Alembic commands ###
