"""add season memberships

Revision ID: 709f75c51f7e
Revises: 28ae01b6e851
Create Date: 2026-08-22 20:50:18.004925
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '709f75c51f7e'
down_revision = '28ae01b6e851'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_season_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MODERATOR', 'MEMBER', name='group_season_role_enum', schema='social'), server_default=sa.text("'MEMBER'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('active_from IS NULL OR active_to IS NULL OR active_from < active_to', name='ck_group_season_memberships_active_window'),
    sa.ForeignKeyConstraint(['group_id'], ['social.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['competition.seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'season_id', 'user_id', name='uq_group_season_memberships_group_season_user'),
    schema='social'
    )
    op.create_index('ix_group_season_memberships_active', 'group_season_memberships', ['group_id', 'season_id', 'is_active'], unique=False, schema='social')
    op.create_index('ix_group_season_memberships_group_season', 'group_season_memberships', ['group_id', 'season_id'], unique=False, schema='social')
    op.create_index('ix_group_season_memberships_user_id', 'group_season_memberships', ['user_id'], unique=False, schema='social')
    op.create_table('team_season_memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', postgresql.ENUM('CAPTAIN', 'MEMBER', name='team_role_enum', schema='social', create_type=False), server_default=sa.text("'MEMBER'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('active_from IS NULL OR active_to IS NULL OR active_from < active_to', name='ck_team_season_memberships_active_window'),
    sa.ForeignKeyConstraint(['group_id', 'team_id'], ['social.teams.group_id', 'social.teams.id'], name='fk_team_season_memberships_group_team', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['social.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['competition.seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'season_id', 'user_id', name='uq_team_season_memberships_group_season_user'),
    sa.UniqueConstraint('team_id', 'season_id', 'user_id', name='uq_team_season_memberships_team_season_user'),
    schema='social'
    )
    op.create_index('ix_team_season_memberships_active', 'team_season_memberships', ['group_id', 'season_id', 'is_active'], unique=False, schema='social')
    op.create_index('ix_team_season_memberships_group_season', 'team_season_memberships', ['group_id', 'season_id'], unique=False, schema='social')
    op.create_index('ix_team_season_memberships_team_id', 'team_season_memberships', ['team_id'], unique=False, schema='social')
    op.create_index('ix_team_season_memberships_user_id', 'team_season_memberships', ['user_id'], unique=False, schema='social')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_team_season_memberships_user_id', table_name='team_season_memberships', schema='social')
    op.drop_index('ix_team_season_memberships_team_id', table_name='team_season_memberships', schema='social')
    op.drop_index('ix_team_season_memberships_group_season', table_name='team_season_memberships', schema='social')
    op.drop_index('ix_team_season_memberships_active', table_name='team_season_memberships', schema='social')
    op.drop_table('team_season_memberships', schema='social')
    op.drop_index('ix_group_season_memberships_user_id', table_name='group_season_memberships', schema='social')
    op.drop_index('ix_group_season_memberships_group_season', table_name='group_season_memberships', schema='social')
    op.drop_index('ix_group_season_memberships_active', table_name='group_season_memberships', schema='social')
    op.drop_table('group_season_memberships', schema='social')
    # ### end Alembic commands ###
