"""add password reset token column invalidated

Revision ID: 7387b5553989
Revises: 3c30bb98da8f
Create Date: 2026-03-12 16:30:43.471873
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7387b5553989'
down_revision = '3c30bb98da8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True), schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_reset_tokens', 'invalidated_at', schema='auth')
    # ### end Alembic commands ###
