"""adding testing sessions in bets

Revision ID: 77c945b5d85a
Revises: 597920bc863b
Create Date: 2026-04-19 15:34:08.373261
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c945b5d85a'
down_revision = '597920bc863b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('testing_event_session_id', sa.Integer(), nullable=True), schema='betting')
    op.create_index('ix_bets_ctx_gp_session_ranking', 'bets', ['bet_context_id', 'event_session_id', 'last_modified_at', 'id'], unique=False, schema='betting', postgresql_where=sa.text('submitted_at IS NOT NULL AND event_session_id IS NOT NULL'))
    op.create_index('uq_bets_user_ctx_gp_session', 'bets', ['user_id', 'bet_context_id', 'event_session_id'], unique=True, schema='betting', postgresql_where=sa.text('event_session_id IS NOT NULL AND testing_event_session_id IS NULL'))
    op.create_index('uq_bets_user_ctx_no_session', 'bets', ['user_id', 'bet_context_id'], unique=True, schema='betting', postgresql_where=sa.text('event_session_id IS NULL AND testing_event_session_id IS NULL'))
    op.create_index('uq_bets_user_ctx_testing_session', 'bets', ['user_id', 'bet_context_id', 'testing_event_session_id'], unique=True, schema='betting', postgresql_where=sa.text('testing_event_session_id IS NOT NULL AND event_session_id IS NULL'))
    op.create_foreign_key(None, 'bets', 'testing_event_sessions', ['testing_event_session_id'], ['id'], source_schema='betting', referent_schema='competition', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bets', schema='betting', type_='foreignkey')
    op.drop_index('uq_bets_user_ctx_testing_session', table_name='bets', schema='betting', postgresql_where=sa.text('testing_event_session_id IS NOT NULL AND event_session_id IS NULL'))
    op.drop_index('uq_bets_user_ctx_no_session', table_name='bets', schema='betting', postgresql_where=sa.text('event_session_id IS NULL AND testing_event_session_id IS NULL'))
    op.drop_index('uq_bets_user_ctx_gp_session', table_name='bets', schema='betting', postgresql_where=sa.text('event_session_id IS NOT NULL AND testing_event_session_id IS NULL'))
    op.drop_index('ix_bets_ctx_gp_session_ranking', table_name='bets', schema='betting', postgresql_where=sa.text('submitted_at IS NOT NULL AND event_session_id IS NOT NULL'))
    op.drop_column('bets', 'testing_event_session_id', schema='betting')
    # ### end Alembic commands ###
