"""add ranking fields to score season aggregates

Revision ID: 8820187e0920
Revises: b605ba844a16
Create Date: 2026-04-21 18:35:49.237427
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8820187e0920'
down_revision = 'b605ba844a16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ranking_event_type = sa.Enum(
        'TESTING_EVENT',
        'RACE_EVENT',
        'SEASON',
        name='ranking_event_type_enum',
        schema='scoring',
    )
    ranking_event_type.create(op.get_bind(), checkfirst=True)

    op.add_column('score_season_aggregates', sa.Column('race_points', sa.Numeric(precision=14, scale=8), server_default=sa.text('0'), nullable=False), schema='scoring')
    op.add_column('score_season_aggregates', sa.Column('testing_points', sa.Numeric(precision=14, scale=8), server_default=sa.text('0'), nullable=False), schema='scoring')
    op.add_column('score_season_aggregates', sa.Column('season_points', sa.Numeric(precision=14, scale=8), server_default=sa.text('0'), nullable=False), schema='scoring')
    op.add_column('score_season_aggregates', sa.Column('extra_points', sa.Numeric(precision=14, scale=8), server_default=sa.text('0'), nullable=False), schema='scoring')
    op.add_column('score_season_aggregates', sa.Column('penalty_points', sa.Numeric(precision=14, scale=8), server_default=sa.text('0'), nullable=False), schema='scoring')
    op.add_column('score_season_aggregates', sa.Column('position', sa.Integer(), nullable=True), schema='scoring')
    op.add_column('score_season_aggregates', sa.Column('previous_position', sa.Integer(), nullable=True), schema='scoring')
    op.add_column('score_season_aggregates', sa.Column('last_event_type', sa.Enum('TESTING_EVENT', 'RACE_EVENT', 'SEASON', name='ranking_event_type_enum', schema='scoring', create_type=False), nullable=True), schema='scoring')
    op.add_column('score_season_aggregates', sa.Column('last_event_label', sa.String(length=200), nullable=True), schema='scoring')
    op.add_column('score_season_aggregates', sa.Column('last_event_order', sa.Integer(), nullable=True), schema='scoring')
    op.add_column('score_season_aggregates', sa.Column('last_scored_at', sa.DateTime(timezone=True), nullable=True), schema='scoring')
    op.create_index('ix_score_season_agg_group_season_position', 'score_season_aggregates', ['group_id', 'season_id', 'position'], unique=False, schema='scoring')
    op.create_index('ix_score_season_agg_group_season_total', 'score_season_aggregates', ['group_id', 'season_id', 'total_points'], unique=False, schema='scoring')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_score_season_agg_group_season_total', table_name='score_season_aggregates', schema='scoring')
    op.drop_index('ix_score_season_agg_group_season_position', table_name='score_season_aggregates', schema='scoring')
    op.drop_column('score_season_aggregates', 'last_scored_at', schema='scoring')
    op.drop_column('score_season_aggregates', 'last_event_order', schema='scoring')
    op.drop_column('score_season_aggregates', 'last_event_label', schema='scoring')
    op.drop_column('score_season_aggregates', 'last_event_type', schema='scoring')
    op.drop_column('score_season_aggregates', 'previous_position', schema='scoring')
    op.drop_column('score_season_aggregates', 'position', schema='scoring')
    op.drop_column('score_season_aggregates', 'penalty_points', schema='scoring')
    op.drop_column('score_season_aggregates', 'extra_points', schema='scoring')
    op.drop_column('score_season_aggregates', 'season_points', schema='scoring')
    op.drop_column('score_season_aggregates', 'testing_points', schema='scoring')
    op.drop_column('score_season_aggregates', 'race_points', schema='scoring')

    ranking_event_type = sa.Enum(
        'TESTING_EVENT',
        'RACE_EVENT',
        'SEASON',
        name='ranking_event_type_enum',
        schema='scoring',
    )
    ranking_event_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
