"""init schemas

Revision ID: a0e163309fdc
Revises: 20260228_0001
Create Date: 2026-03-01 16:45:21.862475
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0e163309fdc'
down_revision = '20260228_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS competition")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='auth'
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('USER', 'ADMIN', 'EDITOR', name='role_name_enum', schema='auth'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='auth'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), server_default=sa.text("'LOCAL'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_username'), 'users', ['username'], unique=True, schema='auth')
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('flag_asset_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='competition'
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='competition'
    )
    op.create_index(op.f('ix_competition_drivers_code'), 'drivers', ['code'], unique=True, schema='competition')
    op.create_table('engines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='competition'
    )
    op.create_index(op.f('ix_competition_engines_code'), 'engines', ['code'], unique=True, schema='competition')
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='competition'
    )
    op.create_index(op.f('ix_competition_seasons_year'), 'seasons', ['year'], unique=True, schema='competition')
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='competition'
    )
    op.create_index(op.f('ix_competition_teams_code'), 'teams', ['code'], unique=True, schema='competition')
    op.create_table('role_permissions',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id', 'role_id'),
    schema='auth'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='auth'
    )
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('map_asset_url', sa.String(length=200), nullable=True),
    sa.Column('image_asset_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['competition.countries.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='competition'
    )
    op.create_table('season_drivers',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PRIMARY', 'RESERVE', 'INACTIVE', name='season_driver_status_enum', schema='competition'), server_default=sa.text("'PRIMARY'"), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['competition.drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['competition.seasons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('season_id', 'driver_id'),
    schema='competition'
    )
    op.create_table('season_engines',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('engine_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['competition.engines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['competition.seasons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('season_id', 'engine_id'),
    schema='competition'
    )
    op.create_table('season_teams',
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['competition.seasons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['competition.teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('season_id', 'team_id'),
    schema='competition'
    )
    op.create_table('race_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('event_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELLED', 'POSTPONED', 'COMPLETED', name='race_event_status_enum', schema='competition'), server_default=sa.text("'SCHEDULED'"), nullable=False),
    sa.Column('status_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['competition.circuits.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['competition.seasons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='competition'
    )
    op.create_index(op.f('ix_competition_race_events_season_id'), 'race_events', ['season_id'], unique=False, schema='competition')
    op.create_table('testing_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=False),
    sa.Column('event_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELLED', 'POSTPONED', 'COMPLETED', name='testing_event_status_enum', schema='competition'), server_default=sa.text("'SCHEDULED'"), nullable=False),
    sa.Column('status_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['competition.circuits.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['competition.seasons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='competition'
    )
    op.create_index(op.f('ix_competition_testing_events_season_id'), 'testing_events', ['season_id'], unique=False, schema='competition')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP SCHEMA IF EXISTS competition CASCADE")
    op.execute("DROP SCHEMA IF EXISTS auth CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('auth_provider', sa.VARCHAR(length=20), server_default=sa.text("'LOCAL'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_competition_testing_events_season_id'), table_name='testing_events', schema='competition')
    op.drop_table('testing_events', schema='competition')
    op.drop_index(op.f('ix_competition_race_events_season_id'), table_name='race_events', schema='competition')
    op.drop_table('race_events', schema='competition')
    op.drop_table('season_teams', schema='competition')
    op.drop_table('season_engines', schema='competition')
    op.drop_table('season_drivers', schema='competition')
    op.drop_table('circuits', schema='competition')
    op.drop_table('user_roles', schema='auth')
    op.drop_table('role_permissions', schema='auth')
    op.drop_index(op.f('ix_competition_teams_code'), table_name='teams', schema='competition')
    op.drop_table('teams', schema='competition')
    op.drop_index(op.f('ix_competition_seasons_year'), table_name='seasons', schema='competition')
    op.drop_table('seasons', schema='competition')
    op.drop_index(op.f('ix_competition_engines_code'), table_name='engines', schema='competition')
    op.drop_table('engines', schema='competition')
    op.drop_index(op.f('ix_competition_drivers_code'), table_name='drivers', schema='competition')
    op.drop_table('drivers', schema='competition')
    op.drop_table('countries', schema='competition')
    op.drop_index(op.f('ix_auth_users_username'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_table('roles', schema='auth')
    op.drop_table('permissions', schema='auth')
    # ### end Alembic commands ###
