"""updating constrainst indexes powerup

Revision ID: a3e3604d1f02
Revises: f6c3b170765e
Create Date: 2026-03-30 15:25:39.103912
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e3604d1f02'
down_revision = 'f6c3b170765e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('powerup_assignments', 'season_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='powerups')
    op.create_index('uq_put_use_all', 'powerup_use_targets', ['powerup_use_id'], unique=True, schema='powerups', postgresql_where=sa.text("target_type = 'ALL'"))
    op.create_index('uq_put_use_group', 'powerup_use_targets', ['powerup_use_id', 'target_group_id', 'target_type'], unique=True, schema='powerups', postgresql_where=sa.text('target_group_id IS NOT NULL'))
    op.create_index('uq_put_use_team', 'powerup_use_targets', ['powerup_use_id', 'target_team_id'], unique=True, schema='powerups', postgresql_where=sa.text('target_team_id IS NOT NULL'))
    op.create_index('uq_put_use_user', 'powerup_use_targets', ['powerup_use_id', 'target_user_id'], unique=True, schema='powerups', postgresql_where=sa.text('target_user_id IS NOT NULL'))
    op.create_index('ix_powerup_uses_context_powerup', 'powerup_uses', ['bet_context_id', 'powerup_id'], unique=False, schema='powerups')
    op.create_index('ix_powerup_uses_group_user', 'powerup_uses', ['group_id', 'user_id'], unique=False, schema='powerups')
    op.create_index('uq_powerup_uses_user_context_powerup', 'powerup_uses', ['user_id', 'group_id', 'bet_context_id', 'powerup_id'], unique=True, schema='powerups', postgresql_where=sa.text('event_session_id IS NULL'))
    op.create_index('uq_powerup_uses_user_session_powerup', 'powerup_uses', ['user_id', 'group_id', 'bet_context_id', 'event_session_id', 'powerup_id'], unique=True, schema='powerups', postgresql_where=sa.text('event_session_id IS NOT NULL'))
    op.drop_index(op.f('ix_scores_context_ranking'), table_name='scores', schema='scoring')
    op.create_index('ix_scores_context_ranking', 'scores', ['bet_context_id', 'total_points', 'computed_at'], unique=False, schema='scoring')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_context_ranking', table_name='scores', schema='scoring')
    op.create_index(op.f('ix_scores_context_ranking'), 'scores', ['bet_context_id', 'total_points', 'computed_at', 'user_id'], unique=False, schema='scoring')
    op.drop_index('uq_powerup_uses_user_session_powerup', table_name='powerup_uses', schema='powerups', postgresql_where=sa.text('event_session_id IS NOT NULL'))
    op.drop_index('uq_powerup_uses_user_context_powerup', table_name='powerup_uses', schema='powerups', postgresql_where=sa.text('event_session_id IS NULL'))
    op.drop_index('ix_powerup_uses_group_user', table_name='powerup_uses', schema='powerups')
    op.drop_index('ix_powerup_uses_context_powerup', table_name='powerup_uses', schema='powerups')
    op.drop_index('uq_put_use_user', table_name='powerup_use_targets', schema='powerups', postgresql_where=sa.text('target_user_id IS NOT NULL'))
    op.drop_index('uq_put_use_team', table_name='powerup_use_targets', schema='powerups', postgresql_where=sa.text('target_team_id IS NOT NULL'))
    op.drop_index('uq_put_use_group', table_name='powerup_use_targets', schema='powerups', postgresql_where=sa.text('target_group_id IS NOT NULL'))
    op.drop_index('uq_put_use_all', table_name='powerup_use_targets', schema='powerups', postgresql_where=sa.text("target_type = 'ALL'"))
    op.alter_column('powerup_assignments', 'season_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='powerups')
    # ### end Alembic commands ###
