"""updating BD teams

Revision ID: ad6188197cf4
Revises: 4e9d15498622
Create Date: 2026-03-30 16:16:24.625256
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6188197cf4'
down_revision = '4e9d15498622'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
