"""updating constrainst indexes scoring

Revision ID: af7d0ef53223
Revises: a3e3604d1f02
Create Date: 2026-03-30 15:48:18.095028
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af7d0ef53223'
down_revision = 'a3e3604d1f02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_session_components', sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='scoring')
    op.drop_column('score_session_components', 'datails_json', schema='scoring')
    op.drop_index(op.f('ix_score_sessions_user_ctx'), table_name='score_sessions', schema='scoring')
    op.create_index('ix_score_sessions_user_ctx', 'score_sessions', ['user_id', 'bet_context_id', 'computed_at'], unique=False, schema='scoring')
    op.drop_index(op.f('ix_scores_context_ranking'), table_name='scores', schema='scoring')
    op.create_index('ix_scores_context_ranking', 'scores', ['bet_context_id', 'total_points', 'computed_at', 'user_id'], unique=False, schema='scoring')
    op.drop_constraint(op.f('uq_scoring_rules_scope_code_target'), 'scoring_rules', schema='scoring', type_='unique')
    op.create_index('uq_scoring_rules_bet_score', 'scoring_rules', ['season_id', 'code', 'bet_score_id'], unique=True, schema='scoring', postgresql_where=sa.text("scope = 'BET_SCORE' AND bet_score_id IS NOT NULL AND bet_context_id IS NULL AND event_session_id IS NULL"))
    op.create_index('uq_scoring_rules_context', 'scoring_rules', ['season_id', 'code', 'bet_context_id'], unique=True, schema='scoring', postgresql_where=sa.text("scope = 'CONTEXT' AND bet_context_id IS NOT NULL AND event_session_id IS NULL AND bet_score_id IS NULL"))
    op.create_index('uq_scoring_rules_global', 'scoring_rules', ['season_id', 'code'], unique=True, schema='scoring', postgresql_where=sa.text("scope = 'GLOBAL' AND bet_context_id IS NULL AND event_session_id IS NULL AND bet_score_id IS NULL"))
    op.create_index('uq_scoring_rules_session', 'scoring_rules', ['season_id', 'code', 'bet_context_id', 'event_session_id'], unique=True, schema='scoring', postgresql_where=sa.text("scope = 'SESSION' AND bet_context_id IS NOT NULL AND event_session_id IS NOT NULL AND bet_score_id IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_scoring_rules_session', table_name='scoring_rules', schema='scoring', postgresql_where=sa.text("scope = 'SESSION' AND bet_context_id IS NOT NULL AND event_session_id IS NOT NULL AND bet_score_id IS NULL"))
    op.drop_index('uq_scoring_rules_global', table_name='scoring_rules', schema='scoring', postgresql_where=sa.text("scope = 'GLOBAL' AND bet_context_id IS NULL AND event_session_id IS NULL AND bet_score_id IS NULL"))
    op.drop_index('uq_scoring_rules_context', table_name='scoring_rules', schema='scoring', postgresql_where=sa.text("scope = 'CONTEXT' AND bet_context_id IS NOT NULL AND event_session_id IS NULL AND bet_score_id IS NULL"))
    op.drop_index('uq_scoring_rules_bet_score', table_name='scoring_rules', schema='scoring', postgresql_where=sa.text("scope = 'BET_SCORE' AND bet_score_id IS NOT NULL AND bet_context_id IS NULL AND event_session_id IS NULL"))
    op.create_unique_constraint(op.f('uq_scoring_rules_scope_code_target'), 'scoring_rules', ['season_id', 'scope', 'code', 'bet_context_id', 'event_session_id', 'bet_score_id'], schema='scoring', postgresql_nulls_not_distinct=False)
    op.drop_index('ix_scores_context_ranking', table_name='scores', schema='scoring')
    op.create_index(op.f('ix_scores_context_ranking'), 'scores', ['bet_context_id', 'total_points', 'computed_at'], unique=False, schema='scoring')
    op.drop_index('ix_score_sessions_user_ctx', table_name='score_sessions', schema='scoring')
    op.create_index(op.f('ix_score_sessions_user_ctx'), 'score_sessions', ['user_id', 'bet_context_id'], unique=False, schema='scoring')
    op.add_column('score_session_components', sa.Column('datails_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='scoring')
    op.drop_column('score_session_components', 'details_json', schema='scoring')
    # ### end Alembic commands ###
