"""scoring testing_event_session

Revision ID: b605ba844a16
Revises: 494e4655e428
Create Date: 2026-04-21 10:53:27.738561
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b605ba844a16'
down_revision = '494e4655e428'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('official_results', sa.Column('testing_event_session_id', sa.Integer(), nullable=True), schema='scoring')
    op.create_index('ix_official_results_testing_session', 'official_results', ['testing_event_session_id'], unique=False, schema='scoring')
    op.create_index('uq_official_results_ctx_testing_session_score', 'official_results', ['bet_context_id', 'testing_event_session_id', 'bet_score_id'], unique=True, schema='scoring', postgresql_where=sa.text('event_session_id IS NULL AND testing_event_session_id IS NOT NULL'))
    op.create_foreign_key(None, 'official_results', 'testing_event_sessions', ['testing_event_session_id'], ['id'], source_schema='scoring', referent_schema='competition', ondelete='RESTRICT')
    op.add_column('result_publications', sa.Column('testing_event_session_id', sa.Integer(), nullable=True), schema='scoring')
    op.create_index('ix_result_publications_testing_session', 'result_publications', ['testing_event_session_id'], unique=False, schema='scoring')
    op.create_index('uq_result_publications_ctx_testing_session', 'result_publications', ['bet_context_id', 'testing_event_session_id'], unique=True, schema='scoring', postgresql_where=sa.text('event_session_id IS NULL AND testing_event_session_id IS NOT NULL'))
    op.create_foreign_key(None, 'result_publications', 'testing_event_sessions', ['testing_event_session_id'], ['id'], source_schema='scoring', referent_schema='competition', ondelete='RESTRICT')
    op.add_column('score_sessions', sa.Column('testing_event_session_id', sa.Integer(), nullable=True), schema='scoring')
    op.alter_column('score_sessions', 'event_session_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='scoring')
    op.drop_constraint(op.f('uq_score_sessions_user_ctx_session'), 'score_sessions', schema='scoring', type_='unique')
    op.create_index('uq_score_sessions_user_ctx_session', 'score_sessions', ['user_id', 'bet_context_id', 'event_session_id'], unique=True, schema='scoring', postgresql_where=sa.text('event_session_id IS NOT NULL AND testing_event_session_id IS NULL'))
    op.create_index('ix_score_sessions_ctx_testing_session_total', 'score_sessions', ['bet_context_id', 'testing_event_session_id', 'total_points'], unique=False, schema='scoring', postgresql_where=sa.text('testing_event_session_id IS NOT NULL'))
    op.create_index('uq_score_sessions_user_ctx_testing_session', 'score_sessions', ['user_id', 'bet_context_id', 'testing_event_session_id'], unique=True, schema='scoring', postgresql_where=sa.text('event_session_id IS NULL AND testing_event_session_id IS NOT NULL'))
    op.create_foreign_key(None, 'score_sessions', 'testing_event_sessions', ['testing_event_session_id'], ['id'], source_schema='scoring', referent_schema='competition', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score_sessions', schema='scoring', type_='foreignkey')
    op.drop_index('uq_score_sessions_user_ctx_testing_session', table_name='score_sessions', schema='scoring', postgresql_where=sa.text('event_session_id IS NULL AND testing_event_session_id IS NOT NULL'))
    op.drop_index('ix_score_sessions_ctx_testing_session_total', table_name='score_sessions', schema='scoring', postgresql_where=sa.text('testing_event_session_id IS NOT NULL'))
    op.drop_index('uq_score_sessions_user_ctx_session', table_name='score_sessions', schema='scoring', postgresql_where=sa.text('event_session_id IS NOT NULL AND testing_event_session_id IS NULL'))
    op.create_unique_constraint(op.f('uq_score_sessions_user_ctx_session'), 'score_sessions', ['user_id', 'bet_context_id', 'event_session_id'], schema='scoring', postgresql_nulls_not_distinct=False)
    op.alter_column('score_sessions', 'event_session_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='scoring')
    op.drop_column('score_sessions', 'testing_event_session_id', schema='scoring')
    op.drop_constraint(None, 'result_publications', schema='scoring', type_='foreignkey')
    op.drop_index('uq_result_publications_ctx_testing_session', table_name='result_publications', schema='scoring', postgresql_where=sa.text('event_session_id IS NULL AND testing_event_session_id IS NOT NULL'))
    op.drop_index('ix_result_publications_testing_session', table_name='result_publications', schema='scoring')
    op.drop_column('result_publications', 'testing_event_session_id', schema='scoring')
    op.drop_constraint(None, 'official_results', schema='scoring', type_='foreignkey')
    op.drop_index('uq_official_results_ctx_testing_session_score', table_name='official_results', schema='scoring', postgresql_where=sa.text('event_session_id IS NULL AND testing_event_session_id IS NOT NULL'))
    op.drop_index('ix_official_results_testing_session', table_name='official_results', schema='scoring')
    op.drop_column('official_results', 'testing_event_session_id', schema='scoring')
    # ### end Alembic commands ###
