"""add powerups schema tables

Revision ID: b8c590a650ef
Revises: 4131f254ef9e
Create Date: 2026-03-03 12:08:44.438237
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8c590a650ef'
down_revision = '4131f254ef9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS powerups")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('powerups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('target_mode', sa.Enum('SINGLE', 'MULTI', 'RULE', name='powerup_target_mode_enum', schema='powerups'), server_default=sa.text("'SINGLE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(code) >= 2', name='ck_powerups_code_minlen'),
    sa.CheckConstraint('length(name) >= 2', name='ck_powerups_name_minlen'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_powerups_code'),
    schema='powerups'
    )
    op.create_index('ix_powerups_is_enabled', 'powerups', ['is_enabled'], unique=False, schema='powerups')
    op.create_table('powerup_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('bet_context_id', sa.Integer(), nullable=True),
    sa.Column('powerup_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('((season_id IS NOT NULL AND bet_context_id IS NULL) OR (season_id IS NULL AND bet_context_id IS NOT NULL))', name='ck_powerup_assignments_scope_xor'),
    sa.CheckConstraint('quantity >= 0', name='ck_powerup_assignments_quantity_nonneg'),
    sa.ForeignKeyConstraint(['bet_context_id'], ['betting.bet_contexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['social.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['powerup_id'], ['powerups.powerups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['competition.seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='powerups'
    )
    op.create_index('ix_powerup_assignments_bet_context_id', 'powerup_assignments', ['bet_context_id'], unique=False, schema='powerups')
    op.create_index('ix_powerup_assignments_group_id', 'powerup_assignments', ['group_id'], unique=False, schema='powerups')
    op.create_index('ix_powerup_assignments_group_user', 'powerup_assignments', ['group_id', 'user_id'], unique=False, schema='powerups')
    op.create_index('ix_powerup_assignments_powerup_id', 'powerup_assignments', ['powerup_id'], unique=False, schema='powerups')
    op.create_index('ix_powerup_assignments_season_id', 'powerup_assignments', ['season_id'], unique=False, schema='powerups')
    op.create_index('ix_powerup_assignments_user_id', 'powerup_assignments', ['user_id'], unique=False, schema='powerups')
    op.create_index('uq_powerup_assignments_event', 'powerup_assignments', ['group_id', 'user_id', 'bet_context_id', 'powerup_id'], unique=True, schema='powerups', postgresql_where=sa.text('bet_context_id IS NOT NULL'))
    op.create_index('uq_powerup_assignments_season', 'powerup_assignments', ['group_id', 'user_id', 'season_id', 'powerup_id'], unique=True, schema='powerups', postgresql_where=sa.text('bet_context_id IS NULL'))
    op.create_table('powerup_restrictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('powerup_id', sa.Integer(), nullable=False),
    sa.Column('bet_context_id', sa.Integer(), nullable=False),
    sa.Column('event_session_id', sa.Integer(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('note IS NULL OR length(note) <= 5000', name='ck_powerup_restrictions_note_len'),
    sa.ForeignKeyConstraint(['bet_context_id'], ['betting.bet_contexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_session_id'], ['competition.event_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['powerup_id'], ['powerups.powerups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='powerups'
    )
    op.create_index('ix_powerup_restrictions_ctx_id', 'powerup_restrictions', ['bet_context_id'], unique=False, schema='powerups')
    op.create_index('ix_powerup_restrictions_is_disabled', 'powerup_restrictions', ['is_disabled'], unique=False, schema='powerups')
    op.create_index('ix_powerup_restrictions_powerup_id', 'powerup_restrictions', ['powerup_id'], unique=False, schema='powerups')
    op.create_index('ix_powerup_restrictions_session_id', 'powerup_restrictions', ['event_session_id'], unique=False, schema='powerups')
    op.create_index('uq_powerup_restrictions_ctx_nosession', 'powerup_restrictions', ['powerup_id', 'bet_context_id'], unique=True, schema='powerups', postgresql_where=sa.text('event_session_id IS NULL'))
    op.create_index('uq_powerup_restrictions_ctx_session', 'powerup_restrictions', ['powerup_id', 'bet_context_id', 'event_session_id'], unique=True, schema='powerups', postgresql_where=sa.text('event_session_id IS NOT NULL'))
    op.create_table('powerup_uses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('bet_context_id', sa.Integer(), nullable=False),
    sa.Column('event_session_id', sa.Integer(), nullable=True),
    sa.Column('powerup_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rule_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['bet_context_id'], ['betting.bet_contexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_session_id'], ['competition.event_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['social.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['powerup_id'], ['powerups.powerups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='powerups'
    )
    op.create_index('ix_powerup_uses_bet_context_id', 'powerup_uses', ['bet_context_id'], unique=False, schema='powerups')
    op.create_index('ix_powerup_uses_event_session_id', 'powerup_uses', ['event_session_id'], unique=False, schema='powerups')
    op.create_index('ix_powerup_uses_group_id', 'powerup_uses', ['group_id'], unique=False, schema='powerups')
    op.create_index('ix_powerup_uses_powerup_id', 'powerup_uses', ['powerup_id'], unique=False, schema='powerups')
    op.create_index('ix_powerup_uses_user_id', 'powerup_uses', ['user_id'], unique=False, schema='powerups')
    op.create_table('powerup_use_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('powerup_use_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('USER', 'TEAM', 'GROUP', 'GROUP_EXCEPT_ACTOR', 'ALL', name='powerup_target_type_enum', schema='powerups'), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('target_team_id', sa.Integer(), nullable=True),
    sa.Column('target_group_id', sa.Integer(), nullable=True),
    sa.Column('rule_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("( (target_type = 'USER' AND target_user_id IS NOT NULL AND target_team_id IS NULL AND target_group_id IS NULL) OR  (target_type = 'TEAM' AND target_team_id IS NOT NULL AND target_user_id IS NULL AND target_group_id IS NULL) OR  (target_type = 'GROUP' AND target_group_id IS NOT NULL AND target_user_id IS NULL AND target_team_id IS NULL) OR  (target_type = 'GROUP_EXCEPT_ACTOR' AND target_group_id IS NOT NULL AND target_user_id IS NULL AND target_team_id IS NULL) OR  (target_type = 'ALL' AND target_user_id IS NULL AND target_team_id IS NULL AND target_group_id IS NULL) )", name='ck_put_target_type_matches_ids'),
    sa.ForeignKeyConstraint(['powerup_use_id'], ['powerups.powerup_uses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_group_id'], ['social.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_team_id'], ['social.teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='powerups'
    )
    op.create_index('ix_put_powerup_use_id', 'powerup_use_targets', ['powerup_use_id'], unique=False, schema='powerups')
    op.create_index('ix_put_target_group_id', 'powerup_use_targets', ['target_group_id'], unique=False, schema='powerups')
    op.create_index('ix_put_target_team_id', 'powerup_use_targets', ['target_team_id'], unique=False, schema='powerups')
    op.create_index('ix_put_target_type', 'powerup_use_targets', ['target_type'], unique=False, schema='powerups')
    op.create_index('ix_put_target_user_id', 'powerup_use_targets', ['target_user_id'], unique=False, schema='powerups')
    op.drop_index(op.f('ix_scores_context_ranking'), table_name='scores', schema='scoring')
    op.create_index('ix_scores_context_ranking', 'scores', ['bet_context_id', 'total_points', 'computed_at'], unique=False, schema='scoring')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_context_ranking', table_name='scores', schema='scoring')
    op.create_index(op.f('ix_scores_context_ranking'), 'scores', ['bet_context_id', 'total_points', 'computed_at', 'user_id'], unique=False, schema='scoring')
    op.drop_index('ix_put_target_user_id', table_name='powerup_use_targets', schema='powerups')
    op.drop_index('ix_put_target_type', table_name='powerup_use_targets', schema='powerups')
    op.drop_index('ix_put_target_team_id', table_name='powerup_use_targets', schema='powerups')
    op.drop_index('ix_put_target_group_id', table_name='powerup_use_targets', schema='powerups')
    op.drop_index('ix_put_powerup_use_id', table_name='powerup_use_targets', schema='powerups')
    op.drop_table('powerup_use_targets', schema='powerups')
    op.drop_index('ix_powerup_uses_user_id', table_name='powerup_uses', schema='powerups')
    op.drop_index('ix_powerup_uses_powerup_id', table_name='powerup_uses', schema='powerups')
    op.drop_index('ix_powerup_uses_group_id', table_name='powerup_uses', schema='powerups')
    op.drop_index('ix_powerup_uses_event_session_id', table_name='powerup_uses', schema='powerups')
    op.drop_index('ix_powerup_uses_bet_context_id', table_name='powerup_uses', schema='powerups')
    op.drop_table('powerup_uses', schema='powerups')
    op.drop_index('uq_powerup_restrictions_ctx_session', table_name='powerup_restrictions', schema='powerups', postgresql_where=sa.text('event_session_id IS NOT NULL'))
    op.drop_index('uq_powerup_restrictions_ctx_nosession', table_name='powerup_restrictions', schema='powerups', postgresql_where=sa.text('event_session_id IS NULL'))
    op.drop_index('ix_powerup_restrictions_session_id', table_name='powerup_restrictions', schema='powerups')
    op.drop_index('ix_powerup_restrictions_powerup_id', table_name='powerup_restrictions', schema='powerups')
    op.drop_index('ix_powerup_restrictions_is_disabled', table_name='powerup_restrictions', schema='powerups')
    op.drop_index('ix_powerup_restrictions_ctx_id', table_name='powerup_restrictions', schema='powerups')
    op.drop_table('powerup_restrictions', schema='powerups')
    op.drop_index('uq_powerup_assignments_season', table_name='powerup_assignments', schema='powerups', postgresql_where=sa.text('bet_context_id IS NULL'))
    op.drop_index('uq_powerup_assignments_event', table_name='powerup_assignments', schema='powerups', postgresql_where=sa.text('bet_context_id IS NOT NULL'))
    op.drop_index('ix_powerup_assignments_user_id', table_name='powerup_assignments', schema='powerups')
    op.drop_index('ix_powerup_assignments_season_id', table_name='powerup_assignments', schema='powerups')
    op.drop_index('ix_powerup_assignments_powerup_id', table_name='powerup_assignments', schema='powerups')
    op.drop_index('ix_powerup_assignments_group_user', table_name='powerup_assignments', schema='powerups')
    op.drop_index('ix_powerup_assignments_group_id', table_name='powerup_assignments', schema='powerups')
    op.drop_index('ix_powerup_assignments_bet_context_id', table_name='powerup_assignments', schema='powerups')
    op.drop_table('powerup_assignments', schema='powerups')
    op.drop_index('ix_powerups_is_enabled', table_name='powerups', schema='powerups')
    op.drop_table('powerups', schema='powerups')
    # ### end Alembic commands ###
