"""adding testing sessions in bets fixed

Revision ID: baee8744ddc2
Revises: 77c945b5d85a
Create Date: 2026-04-19 15:38:24.818636
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baee8744ddc2'
down_revision = '77c945b5d85a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bets_ctx_session_ranking'), table_name='bets', schema='betting', postgresql_where='(submitted_at IS NOT NULL)')
    op.drop_index(op.f('uq_bets_user_ctx_session_notnull'), table_name='bets', schema='betting', postgresql_where='(event_session_id IS NOT NULL)')
    op.drop_index(op.f('uq_bets_user_ctx_session_null'), table_name='bets', schema='betting', postgresql_where='(event_session_id IS NULL)')
    op.create_index('ix_bets_ctx_testing_session_ranking', 'bets', ['bet_context_id', 'testing_event_session_id', 'last_modified_at', 'id'], unique=False, schema='betting', postgresql_where=sa.text('submitted_at IS NOT NULL AND testing_event_session_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bets_ctx_testing_session_ranking', table_name='bets', schema='betting', postgresql_where=sa.text('submitted_at IS NOT NULL AND testing_event_session_id IS NOT NULL'))
    op.create_index(op.f('uq_bets_user_ctx_session_null'), 'bets', ['user_id', 'bet_context_id'], unique=True, schema='betting', postgresql_where='(event_session_id IS NULL)')
    op.create_index(op.f('uq_bets_user_ctx_session_notnull'), 'bets', ['user_id', 'bet_context_id', 'event_session_id'], unique=True, schema='betting', postgresql_where='(event_session_id IS NOT NULL)')
    op.create_index(op.f('ix_bets_ctx_session_ranking'), 'bets', ['bet_context_id', 'event_session_id', 'last_modified_at', 'id'], unique=False, schema='betting', postgresql_where='(submitted_at IS NOT NULL)')
    # ### end Alembic commands ###
