"""add scoring schema tables

Revision ID: c4ef249fbf7c
Revises: 638e1b8eb6b3
Create Date: 2026-03-02 19:04:18.232582
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4ef249fbf7c'
down_revision = '638e1b8eb6b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS scoring")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('official_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bet_context_id', sa.Integer(), nullable=False),
    sa.Column('event_session_id', sa.Integer(), nullable=True),
    sa.Column('bet_score_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'FASTF1', 'OTHER', name='official_result_source_enum', schema='scoring'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("value <> ''", name='ck_official_results_value_not_empty'),
    sa.ForeignKeyConstraint(['bet_context_id'], ['betting.bet_contexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bet_score_id'], ['betting.bet_scores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_session_id'], ['competition.event_sessions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='scoring'
    )
    op.create_index('ix_official_results_ctx', 'official_results', ['bet_context_id'], unique=False, schema='scoring')
    op.create_index('ix_official_results_score', 'official_results', ['bet_score_id'], unique=False, schema='scoring')
    op.create_index('ix_official_results_session', 'official_results', ['event_session_id'], unique=False, schema='scoring')
    op.create_index('uq_official_results_ctx_score_nosession', 'official_results', ['bet_context_id', 'bet_score_id'], unique=True, schema='scoring', postgresql_where=sa.text('event_session_id IS NULL'))
    op.create_index('uq_official_results_ctx_session_score', 'official_results', ['bet_context_id', 'event_session_id', 'bet_score_id'], unique=True, schema='scoring', postgresql_where=sa.text('event_session_id IS NOT NULL'))
    op.create_table('result_publications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bet_context_id', sa.Integer(), nullable=False),
    sa.Column('event_session_id', sa.Integer(), nullable=True),
    sa.Column('published_by_user_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint('note IS NULL OR length(note) <= 5000', name='ck_result_publications_note_len'),
    sa.ForeignKeyConstraint(['bet_context_id'], ['betting.bet_contexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_session_id'], ['competition.event_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='scoring'
    )
    op.create_index('ix_result_publications_ctx', 'result_publications', ['bet_context_id'], unique=False, schema='scoring')
    op.create_index('ix_result_publications_published_at', 'result_publications', ['published_at'], unique=False, schema='scoring')
    op.create_index('ix_result_publications_published_by', 'result_publications', ['published_by_user_id'], unique=False, schema='scoring')
    op.create_index('ix_result_publications_session', 'result_publications', ['event_session_id'], unique=False, schema='scoring')
    op.create_index('uq_result_publications_ctx_nosession', 'result_publications', ['bet_context_id'], unique=True, schema='scoring', postgresql_where=sa.text('event_session_id IS NULL'))
    op.create_index('uq_result_publications_ctx_session', 'result_publications', ['bet_context_id', 'event_session_id'], unique=True, schema='scoring', postgresql_where=sa.text('event_session_id IS NOT NULL'))
    op.create_table('score_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bet_context_id', sa.Integer(), nullable=False),
    sa.Column('event_session_id', sa.Integer(), nullable=False),
    sa.Column('base_points', sa.Numeric(precision=12, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('total_points', sa.Numeric(precision=12, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_points >= 0', name='ck_score_sessions_base_points_nonneg'),
    sa.CheckConstraint('total_points >= 0', name='ck_score_sessions_total_points_nonneg'),
    sa.ForeignKeyConstraint(['bet_context_id'], ['betting.bet_contexts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_session_id'], ['competition.event_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'bet_context_id', 'event_session_id', name='uq_score_sessions_user_ctx_session'),
    schema='scoring'
    )
    op.create_index('ix_score_sessions_ctx_session_total', 'score_sessions', ['bet_context_id', 'event_session_id', 'total_points'], unique=False, schema='scoring')
    op.create_index('ix_score_sessions_user_ctx', 'score_sessions', ['user_id', 'bet_context_id'], unique=False, schema='scoring')
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bet_context_id', sa.Integer(), nullable=False),
    sa.Column('base_points', sa.Numeric(precision=14, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('total_points', sa.Numeric(precision=14, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_points >= 0', name='ck_scores_base_points_nonneg'),
    sa.CheckConstraint('total_points >= 0', name='ck_scores_total_points_nonneg'),
    sa.ForeignKeyConstraint(['bet_context_id'], ['betting.bet_contexts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'bet_context_id', name='uq_scores_user_context'),
    schema='scoring'
    )
    op.create_index('ix_scores_bet_context_id', 'scores', ['bet_context_id'], unique=False, schema='scoring')
    op.create_index('ix_scores_context_ranking', 'scores', ['bet_context_id', 'total_points', 'computed_at'], unique=False, schema='scoring')
    op.create_index('ix_scores_user_id', 'scores', ['user_id'], unique=False, schema='scoring')
    op.create_table('score_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.Enum('BASE', 'EXTRA', 'POWERUP', 'PENALTY', name='score_component_type_enum', schema='scoring'), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('points', sa.Numeric(precision=12, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('points IS NOT NULL', name='ck_score_components_points_notnull'),
    sa.ForeignKeyConstraint(['score_id'], ['scoring.scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score_id', 'component_type', 'code', name='uq_score_components_score_type_code'),
    schema='scoring'
    )
    op.create_index('ix_score_components_score_id', 'score_components', ['score_id'], unique=False, schema='scoring')
    op.create_index('ix_score_components_score_type', 'score_components', ['score_id', 'component_type'], unique=False, schema='scoring')
    op.create_index('ix_score_components_type', 'score_components', ['component_type'], unique=False, schema='scoring')
    op.create_table('score_session_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score_session_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.Enum('BASE', 'EXTRA', 'POWERUP', 'PENALTY', name='score_component_type_enum', schema='scoring'), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('points', sa.Numeric(precision=12, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('datails_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('points IS NOT NULL', name='ck_score_sess_components_points_notnull'),
    sa.ForeignKeyConstraint(['score_session_id'], ['scoring.score_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score_session_id', 'component_type', 'code', name='uq_score_sess_components_sess_type_code'),
    schema='scoring'
    )
    op.create_index('ix_score_sess_components_sess_type', 'score_session_components', ['score_session_id', 'component_type'], unique=False, schema='scoring')
    op.create_index('ix_score_sess_components_session_id', 'score_session_components', ['score_session_id'], unique=False, schema='scoring')
    op.create_index('ix_score_sess_components_type', 'score_session_components', ['component_type'], unique=False, schema='scoring')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_score_sess_components_type', table_name='score_session_components', schema='scoring')
    op.drop_index('ix_score_sess_components_session_id', table_name='score_session_components', schema='scoring')
    op.drop_index('ix_score_sess_components_sess_type', table_name='score_session_components', schema='scoring')
    op.drop_table('score_session_components', schema='scoring')
    op.drop_index('ix_score_components_type', table_name='score_components', schema='scoring')
    op.drop_index('ix_score_components_score_type', table_name='score_components', schema='scoring')
    op.drop_index('ix_score_components_score_id', table_name='score_components', schema='scoring')
    op.drop_table('score_components', schema='scoring')
    op.drop_index('ix_scores_user_id', table_name='scores', schema='scoring')
    op.drop_index('ix_scores_context_ranking', table_name='scores', schema='scoring')
    op.drop_index('ix_scores_bet_context_id', table_name='scores', schema='scoring')
    op.drop_table('scores', schema='scoring')
    op.drop_index('ix_score_sessions_user_ctx', table_name='score_sessions', schema='scoring')
    op.drop_index('ix_score_sessions_ctx_session_total', table_name='score_sessions', schema='scoring')
    op.drop_table('score_sessions', schema='scoring')
    op.drop_index('uq_result_publications_ctx_session', table_name='result_publications', schema='scoring', postgresql_where=sa.text('event_session_id IS NOT NULL'))
    op.drop_index('uq_result_publications_ctx_nosession', table_name='result_publications', schema='scoring', postgresql_where=sa.text('event_session_id IS NULL'))
    op.drop_index('ix_result_publications_session', table_name='result_publications', schema='scoring')
    op.drop_index('ix_result_publications_published_by', table_name='result_publications', schema='scoring')
    op.drop_index('ix_result_publications_published_at', table_name='result_publications', schema='scoring')
    op.drop_index('ix_result_publications_ctx', table_name='result_publications', schema='scoring')
    op.drop_table('result_publications', schema='scoring')
    op.drop_index('uq_official_results_ctx_session_score', table_name='official_results', schema='scoring', postgresql_where=sa.text('event_session_id IS NOT NULL'))
    op.drop_index('uq_official_results_ctx_score_nosession', table_name='official_results', schema='scoring', postgresql_where=sa.text('event_session_id IS NULL'))
    op.drop_index('ix_official_results_session', table_name='official_results', schema='scoring')
    op.drop_index('ix_official_results_score', table_name='official_results', schema='scoring')
    op.drop_index('ix_official_results_ctx', table_name='official_results', schema='scoring')
    op.drop_table('official_results', schema='scoring')
    # ### end Alembic commands ###
