"""adding lock_cutoff and scheduled in event_session, race_event, season, testing, and testing_session

Revision ID: cebdf095fe62
Revises: baee8744ddc2
Create Date: 2026-04-20 15:15:13.756334
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cebdf095fe62'
down_revision = 'baee8744ddc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_sessions', sa.Column('betting_open_at', sa.DateTime(timezone=True), nullable=True), schema='competition')
    op.alter_column('event_sessions', 'lock_cutoff',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               schema='competition')
    op.add_column('race_events', sa.Column('betting_open_at', sa.DateTime(timezone=True), nullable=True), schema='competition')
    op.add_column('race_events', sa.Column('lock_cutoff', sa.DateTime(timezone=True), nullable=True), schema='competition')
    op.add_column('race_events', sa.Column('scheduled_lock_cutoff', sa.DateTime(timezone=True), nullable=True), schema='competition')
    op.add_column('seasons', sa.Column('betting_open_at', sa.DateTime(timezone=True), nullable=True), schema='competition')
    op.add_column('seasons', sa.Column('lock_cutoff', sa.DateTime(timezone=True), nullable=True), schema='competition')
    op.add_column('seasons', sa.Column('scheduled_lock_cutoff', sa.DateTime(timezone=True), nullable=True), schema='competition')
    op.add_column('testing_event_sessions', sa.Column('betting_open_at', sa.DateTime(timezone=True), nullable=True), schema='competition')
    op.add_column('testing_event_sessions', sa.Column('lock_cutoff', sa.DateTime(timezone=True), nullable=True), schema='competition')
    op.add_column('testing_event_sessions', sa.Column('scheduled_lock_cutoff', sa.DateTime(timezone=True), nullable=True), schema='competition')
    op.add_column('testing_events', sa.Column('betting_open_at', sa.DateTime(timezone=True), nullable=True), schema='competition')
    op.add_column('testing_events', sa.Column('lock_cutoff', sa.DateTime(timezone=True), nullable=True), schema='competition')
    op.add_column('testing_events', sa.Column('scheduled_lock_cutoff', sa.DateTime(timezone=True), nullable=True), schema='competition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testing_events', 'scheduled_lock_cutoff', schema='competition')
    op.drop_column('testing_events', 'lock_cutoff', schema='competition')
    op.drop_column('testing_events', 'betting_open_at', schema='competition')
    op.drop_column('testing_event_sessions', 'scheduled_lock_cutoff', schema='competition')
    op.drop_column('testing_event_sessions', 'lock_cutoff', schema='competition')
    op.drop_column('testing_event_sessions', 'betting_open_at', schema='competition')
    op.drop_column('seasons', 'scheduled_lock_cutoff', schema='competition')
    op.drop_column('seasons', 'lock_cutoff', schema='competition')
    op.drop_column('seasons', 'betting_open_at', schema='competition')
    op.drop_column('race_events', 'scheduled_lock_cutoff', schema='competition')
    op.drop_column('race_events', 'lock_cutoff', schema='competition')
    op.drop_column('race_events', 'betting_open_at', schema='competition')
    op.alter_column('event_sessions', 'lock_cutoff',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               schema='competition')
    op.drop_column('event_sessions', 'betting_open_at', schema='competition')
    # ### end Alembic commands ###
