"""add audit logs

Revision ID: d74eee313f38
Revises: 11c316719af4
Create Date: 2026-03-03 15:48:40.529801
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd74eee313f38'
down_revision = '11c316719af4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS audit")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.Text(), nullable=True),
    sa.Column('actor_ip', sa.Text(), nullable=True),
    sa.Column('actor_user_agent', sa.Text(), nullable=True),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('entity_schema', sa.Text(), nullable=False),
    sa.Column('entity_table', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('context_schema', sa.Text(), nullable=True),
    sa.Column('context_table', sa.Text(), nullable=True),
    sa.Column('context_id', sa.Text(), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("action_type <> ''", name='ck_audit_logs_action_type_not_empty'),
    sa.CheckConstraint("entity_id <> ''", name='ck_audit_logs_entity_id_not_empty'),
    sa.CheckConstraint("entity_schema <> ''", name='ck_audit_logs_entity_schema_not_empty'),
    sa.CheckConstraint("entity_table <> ''", name='ck_audit_logs_entity_table_not_empty'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_index('ix_audit_logs_action_type', 'audit_logs', ['action_type'], unique=False, schema='audit')
    op.create_index('ix_audit_logs_actor_user_id', 'audit_logs', ['actor_user_id'], unique=False, schema='audit')
    op.create_index('ix_audit_logs_context', 'audit_logs', ['context_schema', 'context_table', 'context_id'], unique=False, schema='audit')
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False, schema='audit')
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_schema', 'entity_table', 'entity_id'], unique=False, schema='audit')
    
    # ### triggers/functions
    op.execute("""
    CREATE OR REPLACE FUNCTION audit.log_change()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      v_actor_user_id int;
      v_actor_role text;
      v_actor_ip text;
      v_actor_user_agent text;

      v_context_schema text;
      v_context_table text;
      v_context_id text;

      v_entity_id text;
      v_old jsonb;
      v_new jsonb;
    BEGIN
      v_actor_user_id := NULLIF(current_setting('app.actor_user_id', true), '')::int;
      v_actor_role := NULLIF(current_setting('app.actor_role', true), '');
      v_actor_ip := NULLIF(current_setting('app.actor_ip', true), '');
      v_actor_user_agent := NULLIF(current_setting('app.actor_user_agent', true), '');

      v_context_schema := NULLIF(current_setting('app.context_schema', true), '');
      v_context_table  := NULLIF(current_setting('app.context_table', true), '');
      v_context_id     := NULLIF(current_setting('app.context_id', true), '');

      IF (TG_OP = 'INSERT') THEN
        v_old := NULL;
        v_new := to_jsonb(NEW);
        v_entity_id := COALESCE((to_jsonb(NEW)->>'id'), '');
      ELSIF (TG_OP = 'UPDATE') THEN
        v_old := to_jsonb(OLD);
        v_new := to_jsonb(NEW);
        v_entity_id := COALESCE((to_jsonb(NEW)->>'id'), (to_jsonb(OLD)->>'id'), '');
      ELSE
        v_old := to_jsonb(OLD);
        v_new := NULL;
        v_entity_id := COALESCE((to_jsonb(OLD)->>'id'), '');
      END IF;

      INSERT INTO audit.audit_logs (
        actor_user_id, actor_role, actor_ip, actor_user_agent,
        action_type,
        entity_schema, entity_table, entity_id,
        context_schema, context_table, context_id,
        old_data, new_data, metadata
      )
      VALUES (
        v_actor_user_id, v_actor_role, v_actor_ip, v_actor_user_agent,
        TG_OP,
        TG_TABLE_SCHEMA, TG_TABLE_NAME, v_entity_id,
        v_context_schema, v_context_table, v_context_id,
        v_old, v_new,
        jsonb_build_object('txid', txid_current(), 'at', now())
      );

      IF TG_OP = 'DELETE' THEN
        RETURN OLD;
      ELSE
        RETURN NEW;
      END IF;
    END;
    $$;
    """)

    ## Triggers

    op.execute("""
    -- betting
    DROP TRIGGER IF EXISTS trg_audit_betting_bets ON betting.bets;
    CREATE TRIGGER trg_audit_betting_bets
    AFTER INSERT OR UPDATE OR DELETE ON betting.bets
    FOR EACH ROW EXECUTE FUNCTION audit.log_change();

    DROP TRIGGER IF EXISTS trg_audit_betting_bet_picks ON betting.bet_picks;
    CREATE TRIGGER trg_audit_betting_bet_picks
    AFTER INSERT OR UPDATE OR DELETE ON betting.bet_picks
    FOR EACH ROW EXECUTE FUNCTION audit.log_change();

    DROP TRIGGER IF EXISTS trg_audit_betting_bet_contexts ON betting.bet_contexts;
    CREATE TRIGGER trg_audit_betting_bet_contexts
    AFTER INSERT OR UPDATE OR DELETE ON betting.bet_contexts
    FOR EACH ROW EXECUTE FUNCTION audit.log_change();

    DROP TRIGGER IF EXISTS trg_audit_betting_bet_exceptions ON betting.bet_exceptions;
    CREATE TRIGGER trg_audit_betting_bet_exceptions
    AFTER INSERT OR UPDATE OR DELETE ON betting.bet_exceptions
    FOR EACH ROW EXECUTE FUNCTION audit.log_change();

    -- scoring
    DROP TRIGGER IF EXISTS trg_audit_scoring_official_results ON scoring.official_results;
    CREATE TRIGGER trg_audit_scoring_official_results
    AFTER INSERT OR UPDATE OR DELETE ON scoring.official_results
    FOR EACH ROW EXECUTE FUNCTION audit.log_change();

    DROP TRIGGER IF EXISTS trg_audit_scoring_result_publications ON scoring.result_publications;
    CREATE TRIGGER trg_audit_scoring_result_publications
    AFTER INSERT OR UPDATE OR DELETE ON scoring.result_publications
    FOR EACH ROW EXECUTE FUNCTION audit.log_change();

    DROP TRIGGER IF EXISTS trg_audit_scoring_scores ON scoring.scores;
    CREATE TRIGGER trg_audit_scoring_scores
    AFTER INSERT OR UPDATE OR DELETE ON scoring.scores
    FOR EACH ROW EXECUTE FUNCTION audit.log_change();

    DROP TRIGGER IF EXISTS trg_audit_scoring_score_components ON scoring.score_components;
    CREATE TRIGGER trg_audit_scoring_score_components
    AFTER INSERT OR UPDATE OR DELETE ON scoring.score_components
    FOR EACH ROW EXECUTE FUNCTION audit.log_change();

    -- social
    DROP TRIGGER IF EXISTS trg_audit_social_groups ON social.groups;
    CREATE TRIGGER trg_audit_social_groups
    AFTER INSERT OR UPDATE OR DELETE ON social.groups
    FOR EACH ROW EXECUTE FUNCTION audit.log_change();

    DROP TRIGGER IF EXISTS trg_audit_social_group_memberships ON social.group_memberships;
    CREATE TRIGGER trg_audit_social_group_memberships
    AFTER INSERT OR UPDATE OR DELETE ON social.group_memberships
    FOR EACH ROW EXECUTE FUNCTION audit.log_change();

    -- teams
    DROP TRIGGER IF EXISTS trg_audit_social_teams ON social.teams;
    CREATE TRIGGER trg_audit_social_teams
    AFTER INSERT OR UPDATE OR DELETE ON social.teams
    FOR EACH ROW EXECUTE FUNCTION audit.log_change();

    DROP TRIGGER IF EXISTS trg_audit_social_team_memberships ON social.team_memberships;
    CREATE TRIGGER trg_audit_social_team_memberships
    AFTER INSERT OR UPDATE OR DELETE ON social.team_memberships
    FOR EACH ROW EXECUTE FUNCTION audit.log_change();

    -- powerups
    DROP TRIGGER IF EXISTS trg_audit_powerups_powerup_uses ON powerups.powerup_uses;
    CREATE TRIGGER trg_audit_powerups_powerup_uses
    AFTER INSERT OR UPDATE OR DELETE ON powerups.powerup_uses
    FOR EACH ROW EXECUTE FUNCTION audit.log_change();

    DROP TRIGGER IF EXISTS trg_audit_powerups_powerup_use_targets ON powerups.powerup_use_targets;
    CREATE TRIGGER trg_audit_powerups_powerup_use_targets
    AFTER INSERT OR UPDATE OR DELETE ON powerups.powerup_use_targets
    FOR EACH ROW EXECUTE FUNCTION audit.log_change();

    DROP TRIGGER IF EXISTS trg_audit_powerups_powerup_assignments ON powerups.powerup_assignments;
    CREATE TRIGGER trg_audit_powerups_powerup_assignments
    AFTER INSERT OR UPDATE OR DELETE ON powerups.powerup_assignments
    FOR EACH ROW EXECUTE FUNCTION audit.log_change();
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:

    op.execute("""
    DROP TRIGGER IF EXISTS trg_audit_powerups_powerup_assignments ON powerups.powerup_assignments;
    DROP TRIGGER IF EXISTS trg_audit_powerups_powerup_use_targets ON powerups.powerup_use_targets;
    DROP TRIGGER IF EXISTS trg_audit_powerups_powerup_uses ON powerups.powerup_uses;

    DROP TRIGGER IF EXISTS trg_audit_social_team_memberships ON social.team_memberships;
    DROP TRIGGER IF EXISTS trg_audit_social_teams ON social.teams;
    DROP TRIGGER IF EXISTS trg_audit_social_group_memberships ON social.group_memberships;
    DROP TRIGGER IF EXISTS trg_audit_social_groups ON social.groups;

    DROP TRIGGER IF EXISTS trg_audit_scoring_score_components ON scoring.score_components;
    DROP TRIGGER IF EXISTS trg_audit_scoring_scores ON scoring.scores;
    DROP TRIGGER IF EXISTS trg_audit_scoring_result_publications ON scoring.result_publications;
    DROP TRIGGER IF EXISTS trg_audit_scoring_official_results ON scoring.official_results;

    DROP TRIGGER IF EXISTS trg_audit_betting_bet_exceptions ON betting.bet_exceptions;
    DROP TRIGGER IF EXISTS trg_audit_betting_bet_contexts ON betting.bet_contexts;
    DROP TRIGGER IF EXISTS trg_audit_betting_bet_picks ON betting.bet_picks;
    DROP TRIGGER IF EXISTS trg_audit_betting_bets ON betting.bets;
    """)

    op.execute("DROP FUNCTION IF EXISTS audit.log_change();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs', schema='audit')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs', schema='audit')
    op.drop_index('ix_audit_logs_context', table_name='audit_logs', schema='audit')
    op.drop_index('ix_audit_logs_actor_user_id', table_name='audit_logs', schema='audit')
    op.drop_index('ix_audit_logs_action_type', table_name='audit_logs', schema='audit')
    op.drop_table('audit_logs', schema='audit')
    # ### end Alembic commands ###
