"""nuevas tablas Competition

Revision ID: ed5b25ab81de
Revises: a0e163309fdc
Create Date: 2026-03-01 19:35:11.574325
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed5b25ab81de'
down_revision = 'a0e163309fdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1) Asegurar schemas
    op.execute("CREATE SCHEMA IF NOT EXISTS competition")
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")

    # 2) Necesario para ExcludeConstraint con GiST y columnas int (=)
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_event_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.Enum('FP1', 'FP2', 'FP3', 'QUALY', 'SPRINT_QUALY', 'SPRINT', 'RACE', name='event_session_type_enum', schema='competition'), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_cutoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('results_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('results_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['race_event_id'], ['competition.race_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_event_id', 'session_type', name='uq_event_sessions_race_event_session_type'),
    schema='competition'
    )
    op.create_index('ix_event_sessions_race_event_id', 'event_sessions', ['race_event_id'], unique=False, schema='competition')
    op.create_table('driver_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('engine_id', sa.Integer(), nullable=False),
    sa.Column('seat_index', sa.SmallInteger(), nullable=False),
    sa.Column('active_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('race_event_id', sa.Integer(), nullable=True),
    sa.Column('event_session_id', sa.Integer(), nullable=True),
    postgresql.ExcludeConstraint((sa.column('season_id'), '='), (sa.column('team_id'), '='), (sa.column('seat_index'), '='), (sa.text("tstzrange(active_from, active_to, '[)')"), '&&'), where=sa.text('race_event_id IS NULL AND event_session_id IS NULL'), using='gist', name='excl_driver_entries_season_team_seat_time_overlap'),
    sa.CheckConstraint('(active_from IS NULL OR active_to IS NULL OR active_from < active_to)', name='ck_driver_entries_active_window_order'),
    sa.CheckConstraint('NOT (race_event_id IS NOT NULL AND event_session_id IS NOT NULL)', name='ck_driver_entries_not_both_event_and_session'),
    sa.CheckConstraint('seat_index IN (1, 2)', name='ck_driver_entries_seat_index_1_2'),
    sa.ForeignKeyConstraint(['driver_id'], ['competition.drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['engine_id'], ['competition.engines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_session_id'], ['competition.event_sessions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['race_event_id'], ['competition.race_events.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['competition.seasons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['competition.teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='competition'
    )
    op.create_index('ix_driver_entries_season_level_window', 'driver_entries', ['season_id', 'team_id', 'seat_index', 'active_from', 'active_to'], unique=False, schema='competition')
    op.create_index('ix_driver_entries_season_team_seat', 'driver_entries', ['season_id', 'team_id', 'seat_index'], unique=False, schema='competition')
    op.create_index('uq_driver_entries_gp_season_event_team_seat', 'driver_entries', ['season_id', 'race_event_id', 'team_id', 'seat_index'], unique=True, schema='competition', postgresql_where=sa.text('race_event_id IS NOT NULL AND event_session_id IS NULL'))
    op.create_index('uq_driver_entries_session_season_session_team_seat', 'driver_entries', ['season_id', 'event_session_id', 'team_id', 'seat_index'], unique=True, schema='competition', postgresql_where=sa.text('event_session_id IS NOT NULL'))
    op.alter_column('engines', 'code',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=False,
               schema='competition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('engines', 'code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False,
               schema='competition')
    op.drop_index('uq_driver_entries_session_season_session_team_seat', table_name='driver_entries', schema='competition', postgresql_where=sa.text('event_session_id IS NOT NULL'))
    op.drop_index('uq_driver_entries_gp_season_event_team_seat', table_name='driver_entries', schema='competition', postgresql_where=sa.text('race_event_id IS NOT NULL AND event_session_id IS NULL'))
    op.drop_index('ix_driver_entries_season_team_seat', table_name='driver_entries', schema='competition')
    op.drop_index('ix_driver_entries_season_level_window', table_name='driver_entries', schema='competition')
    op.drop_table('driver_entries', schema='competition')
    op.drop_index('ix_event_sessions_race_event_id', table_name='event_sessions', schema='competition')
    op.drop_table('event_sessions', schema='competition')
    # ### end Alembic commands ###
