"""adding new tables for edit permission modification bets, and number of times modified

Revision ID: f1ce9346f29c
Revises: cebdf095fe62
Create Date: 2026-04-20 17:10:14.671425
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ce9346f29c'
down_revision = 'cebdf095fe62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_edit_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bet_context_id', sa.Integer(), nullable=False),
    sa.Column('event_session_id', sa.Integer(), nullable=True),
    sa.Column('testing_event_session_id', sa.Integer(), nullable=True),
    sa.Column('applies_to_all', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_modifications', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('((applies_to_all = true AND group_id IS NULL AND user_id IS NULL AND team_id IS NULL) OR (applies_to_all = false AND (group_id IS NOT NULL OR user_id IS NOT NULL OR team_id IS NOT NULL)))', name='ck_bet_edit_permissions_target'),
    sa.CheckConstraint('NOT (event_session_id IS NOT NULL AND testing_event_session_id IS NOT NULL)', name='ck_bet_edit_permissions_not_both_session_ids'),
    sa.CheckConstraint('max_modifications IS NULL OR max_modifications >= 1', name='ck_bet_edit_permissions_max_modifications_positive'),
    sa.CheckConstraint('starts_at < ends_at', name='ck_bet_edit_permissions_window_order'),
    sa.ForeignKeyConstraint(['bet_context_id'], ['betting.bet_contexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['auth.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_session_id'], ['competition.event_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['social.groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['social.teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['testing_event_session_id'], ['competition.testing_event_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='betting'
    )
    op.create_index('ix_bet_edit_permissions_scope', 'bet_edit_permissions', ['bet_context_id', 'event_session_id', 'testing_event_session_id'], unique=False, schema='betting')
    op.create_index('ix_bet_edit_permissions_window', 'bet_edit_permissions', ['starts_at', 'ends_at'], unique=False, schema='betting')
    op.create_table('bet_submission_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bet_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.CheckConstraint('revision_number >= 1', name='ck_bet_submission_revisions_revision_positive'),
    sa.ForeignKeyConstraint(['bet_id'], ['betting.bets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bet_id', 'revision_number', name='uq_bet_submission_revisions_bet_revision'),
    schema='betting'
    )
    op.create_index('ix_bet_submission_revisions_bet_id', 'bet_submission_revisions', ['bet_id'], unique=False, schema='betting')
    op.add_column('bets', sa.Column('submit_order_int', sa.Integer(), nullable=True), schema='betting')
    op.create_index('ix_bets_context_submit_order', 'bets', ['bet_context_id', 'submit_order_int', 'id'], unique=False, schema='betting', postgresql_where=sa.text('submitted_at IS NOT NULL AND event_session_id IS NULL AND testing_event_session_id IS NULL AND submit_order_int IS NOT NULL'))
    op.create_index('ix_bets_gp_session_submit_order', 'bets', ['bet_context_id', 'event_session_id', 'submit_order_int', 'id'], unique=False, schema='betting', postgresql_where=sa.text('submitted_at IS NOT NULL AND event_session_id IS NOT NULL AND submit_order_int IS NOT NULL'))
    op.create_index('ix_bets_testing_session_submit_order', 'bets', ['bet_context_id', 'testing_event_session_id', 'submit_order_int', 'id'], unique=False, schema='betting', postgresql_where=sa.text('submitted_at IS NOT NULL AND testing_event_session_id IS NOT NULL AND submit_order_int IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bets_testing_session_submit_order', table_name='bets', schema='betting', postgresql_where=sa.text('submitted_at IS NOT NULL AND testing_event_session_id IS NOT NULL AND submit_order_int IS NOT NULL'))
    op.drop_index('ix_bets_gp_session_submit_order', table_name='bets', schema='betting', postgresql_where=sa.text('submitted_at IS NOT NULL AND event_session_id IS NOT NULL AND submit_order_int IS NOT NULL'))
    op.drop_index('ix_bets_context_submit_order', table_name='bets', schema='betting', postgresql_where=sa.text('submitted_at IS NOT NULL AND event_session_id IS NULL AND testing_event_session_id IS NULL AND submit_order_int IS NOT NULL'))
    op.drop_column('bets', 'submit_order_int', schema='betting')
    op.drop_index('ix_bet_submission_revisions_bet_id', table_name='bet_submission_revisions', schema='betting')
    op.drop_table('bet_submission_revisions', schema='betting')
    op.drop_index('ix_bet_edit_permissions_window', table_name='bet_edit_permissions', schema='betting')
    op.drop_index('ix_bet_edit_permissions_scope', table_name='bet_edit_permissions', schema='betting')
    op.drop_table('bet_edit_permissions', schema='betting')
    # ### end Alembic commands ###
