"""updating BD to compare events and session

Revision ID: f22db9fd5552
Revises: 06e992816736
Create Date: 2026-03-31 11:08:38.973094
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22db9fd5552'
down_revision = '06e992816736'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    source_provider_enum = sa.Enum(
        "MANUAL",
        "FASTF1",
        name="source_provider_enum",
        schema="competition",
    )
    source_provider_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "event_sessions",
        sa.Column(
            "source_provider",
            source_provider_enum,
            server_default=sa.text("'MANUAL'"),
            nullable=False,
        ),
        schema="competition",
    )
    op.add_column(
        "event_sessions",
        sa.Column("source_key", sa.String(length=200), nullable=True),
        schema="competition",
    )
    op.create_index(
        "uq_event_sessions_source",
        "event_sessions",
        ["source_provider", "source_key"],
        unique=True,
        schema="competition",
        postgresql_where=sa.text("source_key IS NOT NULL"),
    )

    op.add_column(
        "race_events",
        sa.Column(
            "source_provider",
            source_provider_enum,
            server_default=sa.text("'MANUAL'"),
            nullable=False,
        ),
        schema="competition",
    )
    op.add_column(
        "race_events",
        sa.Column("source_key", sa.String(length=200), nullable=True),
        schema="competition",
    )
    op.create_index(
        "uq_race_events_source",
        "race_events",
        ["source_provider", "source_key"],
        unique=True,
        schema="competition",
        postgresql_where=sa.text("source_key IS NOT NULL"),
    )

    op.add_column(
        "testing_event_sessions",
        sa.Column(
            "source_provider",
            source_provider_enum,
            server_default=sa.text("'MANUAL'"),
            nullable=False,
        ),
        schema="competition",
    )
    op.add_column(
        "testing_event_sessions",
        sa.Column("source_key", sa.String(length=200), nullable=True),
        schema="competition",
    )
    op.create_index(
        "uq_testing_event_sessions_source",
        "testing_event_sessions",
        ["source_provider", "source_key"],
        unique=True,
        schema="competition",
        postgresql_where=sa.text("source_key IS NOT NULL"),
    )

    op.add_column(
        "testing_events",
        sa.Column(
            "source_provider",
            source_provider_enum,
            server_default=sa.text("'MANUAL'"),
            nullable=False,
        ),
        schema="competition",
    )
    op.add_column(
        "testing_events",
        sa.Column("source_key", sa.String(length=200), nullable=True),
        schema="competition",
    )
    op.create_index(
        "uq_testing_events_source",
        "testing_events",
        ["source_provider", "source_key"],
        unique=True,
        schema="competition",
        postgresql_where=sa.text("source_key IS NOT NULL"),
    ) 
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_testing_events_source", table_name="testing_events", schema="competition")
    op.drop_column("testing_events", "source_key", schema="competition")
    op.drop_column("testing_events", "source_provider", schema="competition")

    op.drop_index("uq_testing_event_sessions_source", table_name="testing_event_sessions", schema="competition")
    op.drop_column("testing_event_sessions", "source_key", schema="competition")
    op.drop_column("testing_event_sessions", "source_provider", schema="competition")

    op.drop_index("uq_race_events_source", table_name="race_events", schema="competition")
    op.drop_column("race_events", "source_key", schema="competition")
    op.drop_column("race_events", "source_provider", schema="competition")

    op.drop_index("uq_event_sessions_source", table_name="event_sessions", schema="competition")
    op.drop_column("event_sessions", "source_key", schema="competition")
    op.drop_column("event_sessions", "source_provider", schema="competition")

    source_provider_enum = sa.Enum(
        "MANUAL",
        "FASTF1",
        name="source_provider_enum",
        schema="competition",
    )
    source_provider_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
