"""updating constrainst indexes betting

Revision ID: f6c3b170765e
Revises: 3f4e968db5d6
Create Date: 2026-03-30 15:12:03.539015
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c3b170765e'
down_revision = '3f4e968db5d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bet_contexts_race_event_id', 'bet_contexts', ['race_event_id'], unique=False, schema='betting')
    op.create_index('ix_bet_contexts_testing_event_id', 'bet_contexts', ['testing_event_id'], unique=False, schema='betting')
    op.drop_index(op.f('ix_scores_context_ranking'), table_name='scores', schema='scoring')
    op.create_index('ix_scores_context_ranking', 'scores', ['bet_context_id', 'total_points', 'computed_at', 'user_id'], unique=False, schema='scoring')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_context_ranking', table_name='scores', schema='scoring')
    op.create_index(op.f('ix_scores_context_ranking'), 'scores', ['bet_context_id', 'total_points', 'computed_at'], unique=False, schema='scoring')
    op.drop_index('ix_bet_contexts_testing_event_id', table_name='bet_contexts', schema='betting')
    op.drop_index('ix_bet_contexts_race_event_id', table_name='bet_contexts', schema='betting')
    # ### end Alembic commands ###
