COMPETITION_MANAGE = "COMPETITION_MANAGE"
BETTING_MANAGE = "BETTING_MANAGE"
SCORING_MANAGE = "SCORING_MANAGE"
POWERUPS_MANAGE = "POWERUPS_MANAGE"
RULES_MANAGE = "RULES_MANAGE"

ALL_PERMISSION_CODES = (
    COMPETITION_MANAGE,
    BETTING_MANAGE,
    SCORING_MANAGE,
    POWERUPS_MANAGE,
    RULES_MANAGE,
)
